/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>tilos2</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.ApiAuditRecord, java.lang.Integer> IDENTITY_API_AUDIT = Identities0.IDENTITY_API_AUDIT;
	public static final org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.AuditRecord, java.lang.Integer> IDENTITY_AUDIT = Identities0.IDENTITY_AUDIT;
	public static final org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.AuthorRecord, java.lang.Integer> IDENTITY_AUTHOR = Identities0.IDENTITY_AUTHOR;
	public static final org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord, java.lang.Integer> IDENTITY_BOOKMARK = Identities0.IDENTITY_BOOKMARK;
	public static final org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.ChangePasswordRecord, java.lang.Integer> IDENTITY_CHANGE_PASSWORD = Identities0.IDENTITY_CHANGE_PASSWORD;
	public static final org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.ContributionRecord, java.lang.Integer> IDENTITY_CONTRIBUTION = Identities0.IDENTITY_CONTRIBUTION;
	public static final org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord, java.lang.Integer> IDENTITY_EPISODE = Identities0.IDENTITY_EPISODE;
	public static final org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.ListenerStatRecord, java.lang.Integer> IDENTITY_LISTENER_STAT = Identities0.IDENTITY_LISTENER_STAT;
	public static final org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.MixRecord, java.lang.Integer> IDENTITY_MIX = Identities0.IDENTITY_MIX;
	public static final org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord, java.lang.Integer> IDENTITY_RADIOSHOW = Identities0.IDENTITY_RADIOSHOW;
	public static final org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.RoleRecord, java.lang.Integer> IDENTITY_ROLE = Identities0.IDENTITY_ROLE;
	public static final org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord, java.lang.Integer> IDENTITY_SCHEDULING = Identities0.IDENTITY_SCHEDULING;
	public static final org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.TagRecord, java.lang.Integer> IDENTITY_TAG = Identities0.IDENTITY_TAG;
	public static final org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord, java.lang.Integer> IDENTITY_TEXTCONTENT = Identities0.IDENTITY_TEXTCONTENT;
	public static final org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.UrlRecord, java.lang.Integer> IDENTITY_URL = Identities0.IDENTITY_URL;
	public static final org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.UserRecord, java.lang.Integer> IDENTITY_USER = Identities0.IDENTITY_USER;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ApiAuditRecord> KEY_API_AUDIT_PRIMARY = UniqueKeys0.KEY_API_AUDIT_PRIMARY;
	public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.AuditRecord> KEY_AUDIT_PRIMARY = UniqueKeys0.KEY_AUDIT_PRIMARY;
	public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.AuthorRecord> KEY_AUTHOR_PRIMARY = UniqueKeys0.KEY_AUTHOR_PRIMARY;
	public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.AuthorRecord> KEY_AUTHOR_UNIQ_BDAFD8C8A76ED395 = UniqueKeys0.KEY_AUTHOR_UNIQ_BDAFD8C8A76ED395;
	public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.AuthorUrlRecord> KEY_AUTHOR_URL_PRIMARY = UniqueKeys0.KEY_AUTHOR_URL_PRIMARY;
	public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.AuthorUrlRecord> KEY_AUTHOR_URL_UNIQ_1531912281CFDAE7 = UniqueKeys0.KEY_AUTHOR_URL_UNIQ_1531912281CFDAE7;
	public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord> KEY_BOOKMARK_PRIMARY = UniqueKeys0.KEY_BOOKMARK_PRIMARY;
	public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ChangePasswordRecord> KEY_CHANGE_PASSWORD_PRIMARY = UniqueKeys0.KEY_CHANGE_PASSWORD_PRIMARY;
	public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ChangePasswordRecord> KEY_CHANGE_PASSWORD_UNIQ_9A385A3BA76ED395 = UniqueKeys0.KEY_CHANGE_PASSWORD_UNIQ_9A385A3BA76ED395;
	public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ContributionRecord> KEY_CONTRIBUTION_PRIMARY = UniqueKeys0.KEY_CONTRIBUTION_PRIMARY;
	public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord> KEY_EPISODE_PRIMARY = UniqueKeys0.KEY_EPISODE_PRIMARY;
	public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord> KEY_EPISODE_UNIQ_DDAA1CDA3A333134 = UniqueKeys0.KEY_EPISODE_UNIQ_DDAA1CDA3A333134;
	public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ListenerStatRecord> KEY_LISTENER_STAT_PRIMARY = UniqueKeys0.KEY_LISTENER_STAT_PRIMARY;
	public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.MigrationVersionsRecord> KEY_MIGRATION_VERSIONS_PRIMARY = UniqueKeys0.KEY_MIGRATION_VERSIONS_PRIMARY;
	public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.MixRecord> KEY_MIX_PRIMARY = UniqueKeys0.KEY_MIX_PRIMARY;
	public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord> KEY_RADIOSHOW_PRIMARY = UniqueKeys0.KEY_RADIOSHOW_PRIMARY;
	public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.RoleRecord> KEY_ROLE_PRIMARY = UniqueKeys0.KEY_ROLE_PRIMARY;
	public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.RoleRecord> KEY_ROLE_UNIQ_57698A6AA44B56EA = UniqueKeys0.KEY_ROLE_UNIQ_57698A6AA44B56EA;
	public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord> KEY_SCHEDULING_PRIMARY = UniqueKeys0.KEY_SCHEDULING_PRIMARY;
	public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ShowUrlRecord> KEY_SHOW_URL_PRIMARY = UniqueKeys0.KEY_SHOW_URL_PRIMARY;
	public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ShowUrlRecord> KEY_SHOW_URL_UNIQ_D5AD498081CFDAE7 = UniqueKeys0.KEY_SHOW_URL_UNIQ_D5AD498081CFDAE7;
	public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.TagRecord> KEY_TAG_PRIMARY = UniqueKeys0.KEY_TAG_PRIMARY;
	public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.TagTextcontentRecord> KEY_TAG_TEXTCONTENT_PRIMARY = UniqueKeys0.KEY_TAG_TEXTCONTENT_PRIMARY;
	public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord> KEY_TEXTCONTENT_PRIMARY = UniqueKeys0.KEY_TEXTCONTENT_PRIMARY;
	public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.UrlRecord> KEY_URL_PRIMARY = UniqueKeys0.KEY_URL_PRIMARY;
	public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.AuthorRecord, hu.tilos.radio.jooqmodel.tables.records.UserRecord> FK_BDAFD8C8A76ED395 = ForeignKeys0.FK_BDAFD8C8A76ED395;
	public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.AuthorUrlRecord, hu.tilos.radio.jooqmodel.tables.records.AuthorRecord> FK_15319122F675F31B = ForeignKeys0.FK_15319122F675F31B;
	public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.AuthorUrlRecord, hu.tilos.radio.jooqmodel.tables.records.UrlRecord> FK_1531912281CFDAE7 = ForeignKeys0.FK_1531912281CFDAE7;
	public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord, hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord> FK_DA62921D4E549204 = ForeignKeys0.FK_DA62921D4E549204;
	public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord, hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord> FK_DA62921D362B62A0 = ForeignKeys0.FK_DA62921D362B62A0;
	public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord, hu.tilos.radio.jooqmodel.tables.records.UserRecord> FK_DA62921DA76ED395 = ForeignKeys0.FK_DA62921DA76ED395;
	public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.ChangePasswordRecord, hu.tilos.radio.jooqmodel.tables.records.UserRecord> FK_9A385A3BA76ED395 = ForeignKeys0.FK_9A385A3BA76ED395;
	public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.ContributionRecord, hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord> FK_EA351E154E549204 = ForeignKeys0.FK_EA351E154E549204;
	public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.ContributionRecord, hu.tilos.radio.jooqmodel.tables.records.AuthorRecord> FK_EA351E15F675F31B = ForeignKeys0.FK_EA351E15F675F31B;
	public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord, hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord> FK_DDAA1CDA4E549204 = ForeignKeys0.FK_DDAA1CDA4E549204;
	public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord, hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord> FK_DDAA1CDA3A333134 = ForeignKeys0.FK_DDAA1CDA3A333134;
	public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.MixRecord, hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord> FK_55AFA881D0C1FC64 = ForeignKeys0.FK_55AFA881D0C1FC64;
	public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.RoleRecord, hu.tilos.radio.jooqmodel.tables.records.RoleRecord> FK_57698A6AA44B56EA = ForeignKeys0.FK_57698A6AA44B56EA;
	public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord, hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord> FK_FD931BF54E549204 = ForeignKeys0.FK_FD931BF54E549204;
	public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.ShowUrlRecord, hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord> FK_D5AD49804E549204 = ForeignKeys0.FK_D5AD49804E549204;
	public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.ShowUrlRecord, hu.tilos.radio.jooqmodel.tables.records.UrlRecord> FK_D5AD498081CFDAE7 = ForeignKeys0.FK_D5AD498081CFDAE7;
	public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.TagTextcontentRecord, hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord> FK_EB334393A333134 = ForeignKeys0.FK_EB334393A333134;
	public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.TagTextcontentRecord, hu.tilos.radio.jooqmodel.tables.records.TagRecord> FK_EB33439BAD26311 = ForeignKeys0.FK_EB33439BAD26311;
	public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.UserRecord, hu.tilos.radio.jooqmodel.tables.records.RoleRecord> FK_8D93D649D60322AC = ForeignKeys0.FK_8D93D649D60322AC;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.ApiAuditRecord, java.lang.Integer> IDENTITY_API_AUDIT = createIdentity(hu.tilos.radio.jooqmodel.tables.ApiAudit.API_AUDIT, hu.tilos.radio.jooqmodel.tables.ApiAudit.API_AUDIT.ID);
		public static org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.AuditRecord, java.lang.Integer> IDENTITY_AUDIT = createIdentity(hu.tilos.radio.jooqmodel.tables.Audit.AUDIT, hu.tilos.radio.jooqmodel.tables.Audit.AUDIT.ID);
		public static org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.AuthorRecord, java.lang.Integer> IDENTITY_AUTHOR = createIdentity(hu.tilos.radio.jooqmodel.tables.Author.AUTHOR, hu.tilos.radio.jooqmodel.tables.Author.AUTHOR.ID);
		public static org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord, java.lang.Integer> IDENTITY_BOOKMARK = createIdentity(hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK, hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK.ID);
		public static org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.ChangePasswordRecord, java.lang.Integer> IDENTITY_CHANGE_PASSWORD = createIdentity(hu.tilos.radio.jooqmodel.tables.ChangePassword.CHANGE_PASSWORD, hu.tilos.radio.jooqmodel.tables.ChangePassword.CHANGE_PASSWORD.ID);
		public static org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.ContributionRecord, java.lang.Integer> IDENTITY_CONTRIBUTION = createIdentity(hu.tilos.radio.jooqmodel.tables.Contribution.CONTRIBUTION, hu.tilos.radio.jooqmodel.tables.Contribution.CONTRIBUTION.ID);
		public static org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord, java.lang.Integer> IDENTITY_EPISODE = createIdentity(hu.tilos.radio.jooqmodel.tables.Episode.EPISODE, hu.tilos.radio.jooqmodel.tables.Episode.EPISODE.ID);
		public static org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.ListenerStatRecord, java.lang.Integer> IDENTITY_LISTENER_STAT = createIdentity(hu.tilos.radio.jooqmodel.tables.ListenerStat.LISTENER_STAT, hu.tilos.radio.jooqmodel.tables.ListenerStat.LISTENER_STAT.ID);
		public static org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.MixRecord, java.lang.Integer> IDENTITY_MIX = createIdentity(hu.tilos.radio.jooqmodel.tables.Mix.MIX, hu.tilos.radio.jooqmodel.tables.Mix.MIX.ID);
		public static org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord, java.lang.Integer> IDENTITY_RADIOSHOW = createIdentity(hu.tilos.radio.jooqmodel.tables.Radioshow.RADIOSHOW, hu.tilos.radio.jooqmodel.tables.Radioshow.RADIOSHOW.ID);
		public static org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.RoleRecord, java.lang.Integer> IDENTITY_ROLE = createIdentity(hu.tilos.radio.jooqmodel.tables.Role.ROLE, hu.tilos.radio.jooqmodel.tables.Role.ROLE.ID);
		public static org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord, java.lang.Integer> IDENTITY_SCHEDULING = createIdentity(hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING, hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING.ID);
		public static org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.TagRecord, java.lang.Integer> IDENTITY_TAG = createIdentity(hu.tilos.radio.jooqmodel.tables.Tag.TAG, hu.tilos.radio.jooqmodel.tables.Tag.TAG.ID);
		public static org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord, java.lang.Integer> IDENTITY_TEXTCONTENT = createIdentity(hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT, hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT.ID);
		public static org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.UrlRecord, java.lang.Integer> IDENTITY_URL = createIdentity(hu.tilos.radio.jooqmodel.tables.Url.URL, hu.tilos.radio.jooqmodel.tables.Url.URL.ID);
		public static org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.UserRecord, java.lang.Integer> IDENTITY_USER = createIdentity(hu.tilos.radio.jooqmodel.tables.User.USER, hu.tilos.radio.jooqmodel.tables.User.USER.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ApiAuditRecord> KEY_API_AUDIT_PRIMARY = createUniqueKey(hu.tilos.radio.jooqmodel.tables.ApiAudit.API_AUDIT, hu.tilos.radio.jooqmodel.tables.ApiAudit.API_AUDIT.ID);
		public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.AuditRecord> KEY_AUDIT_PRIMARY = createUniqueKey(hu.tilos.radio.jooqmodel.tables.Audit.AUDIT, hu.tilos.radio.jooqmodel.tables.Audit.AUDIT.ID);
		public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.AuthorRecord> KEY_AUTHOR_PRIMARY = createUniqueKey(hu.tilos.radio.jooqmodel.tables.Author.AUTHOR, hu.tilos.radio.jooqmodel.tables.Author.AUTHOR.ID);
		public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.AuthorRecord> KEY_AUTHOR_UNIQ_BDAFD8C8A76ED395 = createUniqueKey(hu.tilos.radio.jooqmodel.tables.Author.AUTHOR, hu.tilos.radio.jooqmodel.tables.Author.AUTHOR.USER_ID);
		public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.AuthorUrlRecord> KEY_AUTHOR_URL_PRIMARY = createUniqueKey(hu.tilos.radio.jooqmodel.tables.AuthorUrl.AUTHOR_URL, hu.tilos.radio.jooqmodel.tables.AuthorUrl.AUTHOR_URL.AUTHOR_ID, hu.tilos.radio.jooqmodel.tables.AuthorUrl.AUTHOR_URL.URL_ID);
		public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.AuthorUrlRecord> KEY_AUTHOR_URL_UNIQ_1531912281CFDAE7 = createUniqueKey(hu.tilos.radio.jooqmodel.tables.AuthorUrl.AUTHOR_URL, hu.tilos.radio.jooqmodel.tables.AuthorUrl.AUTHOR_URL.URL_ID);
		public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord> KEY_BOOKMARK_PRIMARY = createUniqueKey(hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK, hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK.ID);
		public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ChangePasswordRecord> KEY_CHANGE_PASSWORD_PRIMARY = createUniqueKey(hu.tilos.radio.jooqmodel.tables.ChangePassword.CHANGE_PASSWORD, hu.tilos.radio.jooqmodel.tables.ChangePassword.CHANGE_PASSWORD.ID);
		public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ChangePasswordRecord> KEY_CHANGE_PASSWORD_UNIQ_9A385A3BA76ED395 = createUniqueKey(hu.tilos.radio.jooqmodel.tables.ChangePassword.CHANGE_PASSWORD, hu.tilos.radio.jooqmodel.tables.ChangePassword.CHANGE_PASSWORD.USER_ID);
		public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ContributionRecord> KEY_CONTRIBUTION_PRIMARY = createUniqueKey(hu.tilos.radio.jooqmodel.tables.Contribution.CONTRIBUTION, hu.tilos.radio.jooqmodel.tables.Contribution.CONTRIBUTION.ID);
		public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord> KEY_EPISODE_PRIMARY = createUniqueKey(hu.tilos.radio.jooqmodel.tables.Episode.EPISODE, hu.tilos.radio.jooqmodel.tables.Episode.EPISODE.ID);
		public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord> KEY_EPISODE_UNIQ_DDAA1CDA3A333134 = createUniqueKey(hu.tilos.radio.jooqmodel.tables.Episode.EPISODE, hu.tilos.radio.jooqmodel.tables.Episode.EPISODE.TEXTCONTENT_ID);
		public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ListenerStatRecord> KEY_LISTENER_STAT_PRIMARY = createUniqueKey(hu.tilos.radio.jooqmodel.tables.ListenerStat.LISTENER_STAT, hu.tilos.radio.jooqmodel.tables.ListenerStat.LISTENER_STAT.ID);
		public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.MigrationVersionsRecord> KEY_MIGRATION_VERSIONS_PRIMARY = createUniqueKey(hu.tilos.radio.jooqmodel.tables.MigrationVersions.MIGRATION_VERSIONS, hu.tilos.radio.jooqmodel.tables.MigrationVersions.MIGRATION_VERSIONS.VERSION);
		public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.MixRecord> KEY_MIX_PRIMARY = createUniqueKey(hu.tilos.radio.jooqmodel.tables.Mix.MIX, hu.tilos.radio.jooqmodel.tables.Mix.MIX.ID);
		public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord> KEY_RADIOSHOW_PRIMARY = createUniqueKey(hu.tilos.radio.jooqmodel.tables.Radioshow.RADIOSHOW, hu.tilos.radio.jooqmodel.tables.Radioshow.RADIOSHOW.ID);
		public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.RoleRecord> KEY_ROLE_PRIMARY = createUniqueKey(hu.tilos.radio.jooqmodel.tables.Role.ROLE, hu.tilos.radio.jooqmodel.tables.Role.ROLE.ID);
		public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.RoleRecord> KEY_ROLE_UNIQ_57698A6AA44B56EA = createUniqueKey(hu.tilos.radio.jooqmodel.tables.Role.ROLE, hu.tilos.radio.jooqmodel.tables.Role.ROLE.PARENT_ROLE_ID);
		public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord> KEY_SCHEDULING_PRIMARY = createUniqueKey(hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING, hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING.ID);
		public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ShowUrlRecord> KEY_SHOW_URL_PRIMARY = createUniqueKey(hu.tilos.radio.jooqmodel.tables.ShowUrl.SHOW_URL, hu.tilos.radio.jooqmodel.tables.ShowUrl.SHOW_URL.RADIOSHOW_ID, hu.tilos.radio.jooqmodel.tables.ShowUrl.SHOW_URL.URL_ID);
		public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ShowUrlRecord> KEY_SHOW_URL_UNIQ_D5AD498081CFDAE7 = createUniqueKey(hu.tilos.radio.jooqmodel.tables.ShowUrl.SHOW_URL, hu.tilos.radio.jooqmodel.tables.ShowUrl.SHOW_URL.URL_ID);
		public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.TagRecord> KEY_TAG_PRIMARY = createUniqueKey(hu.tilos.radio.jooqmodel.tables.Tag.TAG, hu.tilos.radio.jooqmodel.tables.Tag.TAG.ID);
		public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.TagTextcontentRecord> KEY_TAG_TEXTCONTENT_PRIMARY = createUniqueKey(hu.tilos.radio.jooqmodel.tables.TagTextcontent.TAG_TEXTCONTENT, hu.tilos.radio.jooqmodel.tables.TagTextcontent.TAG_TEXTCONTENT.TEXTCONTENT_ID, hu.tilos.radio.jooqmodel.tables.TagTextcontent.TAG_TEXTCONTENT.TAG_ID);
		public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord> KEY_TEXTCONTENT_PRIMARY = createUniqueKey(hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT, hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT.ID);
		public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.UrlRecord> KEY_URL_PRIMARY = createUniqueKey(hu.tilos.radio.jooqmodel.tables.Url.URL, hu.tilos.radio.jooqmodel.tables.Url.URL.ID);
		public static final org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.UserRecord> KEY_USER_PRIMARY = createUniqueKey(hu.tilos.radio.jooqmodel.tables.User.USER, hu.tilos.radio.jooqmodel.tables.User.USER.ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.AuthorRecord, hu.tilos.radio.jooqmodel.tables.records.UserRecord> FK_BDAFD8C8A76ED395 = createForeignKey(hu.tilos.radio.jooqmodel.Keys.KEY_USER_PRIMARY, hu.tilos.radio.jooqmodel.tables.Author.AUTHOR, hu.tilos.radio.jooqmodel.tables.Author.AUTHOR.USER_ID);
		public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.AuthorUrlRecord, hu.tilos.radio.jooqmodel.tables.records.AuthorRecord> FK_15319122F675F31B = createForeignKey(hu.tilos.radio.jooqmodel.Keys.KEY_AUTHOR_PRIMARY, hu.tilos.radio.jooqmodel.tables.AuthorUrl.AUTHOR_URL, hu.tilos.radio.jooqmodel.tables.AuthorUrl.AUTHOR_URL.AUTHOR_ID);
		public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.AuthorUrlRecord, hu.tilos.radio.jooqmodel.tables.records.UrlRecord> FK_1531912281CFDAE7 = createForeignKey(hu.tilos.radio.jooqmodel.Keys.KEY_URL_PRIMARY, hu.tilos.radio.jooqmodel.tables.AuthorUrl.AUTHOR_URL, hu.tilos.radio.jooqmodel.tables.AuthorUrl.AUTHOR_URL.URL_ID);
		public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord, hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord> FK_DA62921D4E549204 = createForeignKey(hu.tilos.radio.jooqmodel.Keys.KEY_RADIOSHOW_PRIMARY, hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK, hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK.RADIOSHOW_ID);
		public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord, hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord> FK_DA62921D362B62A0 = createForeignKey(hu.tilos.radio.jooqmodel.Keys.KEY_EPISODE_PRIMARY, hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK, hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK.EPISODE_ID);
		public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord, hu.tilos.radio.jooqmodel.tables.records.UserRecord> FK_DA62921DA76ED395 = createForeignKey(hu.tilos.radio.jooqmodel.Keys.KEY_USER_PRIMARY, hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK, hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK.USER_ID);
		public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.ChangePasswordRecord, hu.tilos.radio.jooqmodel.tables.records.UserRecord> FK_9A385A3BA76ED395 = createForeignKey(hu.tilos.radio.jooqmodel.Keys.KEY_USER_PRIMARY, hu.tilos.radio.jooqmodel.tables.ChangePassword.CHANGE_PASSWORD, hu.tilos.radio.jooqmodel.tables.ChangePassword.CHANGE_PASSWORD.USER_ID);
		public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.ContributionRecord, hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord> FK_EA351E154E549204 = createForeignKey(hu.tilos.radio.jooqmodel.Keys.KEY_RADIOSHOW_PRIMARY, hu.tilos.radio.jooqmodel.tables.Contribution.CONTRIBUTION, hu.tilos.radio.jooqmodel.tables.Contribution.CONTRIBUTION.RADIOSHOW_ID);
		public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.ContributionRecord, hu.tilos.radio.jooqmodel.tables.records.AuthorRecord> FK_EA351E15F675F31B = createForeignKey(hu.tilos.radio.jooqmodel.Keys.KEY_AUTHOR_PRIMARY, hu.tilos.radio.jooqmodel.tables.Contribution.CONTRIBUTION, hu.tilos.radio.jooqmodel.tables.Contribution.CONTRIBUTION.AUTHOR_ID);
		public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord, hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord> FK_DDAA1CDA4E549204 = createForeignKey(hu.tilos.radio.jooqmodel.Keys.KEY_RADIOSHOW_PRIMARY, hu.tilos.radio.jooqmodel.tables.Episode.EPISODE, hu.tilos.radio.jooqmodel.tables.Episode.EPISODE.RADIOSHOW_ID);
		public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord, hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord> FK_DDAA1CDA3A333134 = createForeignKey(hu.tilos.radio.jooqmodel.Keys.KEY_TEXTCONTENT_PRIMARY, hu.tilos.radio.jooqmodel.tables.Episode.EPISODE, hu.tilos.radio.jooqmodel.tables.Episode.EPISODE.TEXTCONTENT_ID);
		public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.MixRecord, hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord> FK_55AFA881D0C1FC64 = createForeignKey(hu.tilos.radio.jooqmodel.Keys.KEY_RADIOSHOW_PRIMARY, hu.tilos.radio.jooqmodel.tables.Mix.MIX, hu.tilos.radio.jooqmodel.tables.Mix.MIX.SHOW_ID);
		public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.RoleRecord, hu.tilos.radio.jooqmodel.tables.records.RoleRecord> FK_57698A6AA44B56EA = createForeignKey(hu.tilos.radio.jooqmodel.Keys.KEY_ROLE_PRIMARY, hu.tilos.radio.jooqmodel.tables.Role.ROLE, hu.tilos.radio.jooqmodel.tables.Role.ROLE.PARENT_ROLE_ID);
		public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord, hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord> FK_FD931BF54E549204 = createForeignKey(hu.tilos.radio.jooqmodel.Keys.KEY_RADIOSHOW_PRIMARY, hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING, hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING.RADIOSHOW_ID);
		public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.ShowUrlRecord, hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord> FK_D5AD49804E549204 = createForeignKey(hu.tilos.radio.jooqmodel.Keys.KEY_RADIOSHOW_PRIMARY, hu.tilos.radio.jooqmodel.tables.ShowUrl.SHOW_URL, hu.tilos.radio.jooqmodel.tables.ShowUrl.SHOW_URL.RADIOSHOW_ID);
		public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.ShowUrlRecord, hu.tilos.radio.jooqmodel.tables.records.UrlRecord> FK_D5AD498081CFDAE7 = createForeignKey(hu.tilos.radio.jooqmodel.Keys.KEY_URL_PRIMARY, hu.tilos.radio.jooqmodel.tables.ShowUrl.SHOW_URL, hu.tilos.radio.jooqmodel.tables.ShowUrl.SHOW_URL.URL_ID);
		public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.TagTextcontentRecord, hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord> FK_EB334393A333134 = createForeignKey(hu.tilos.radio.jooqmodel.Keys.KEY_TEXTCONTENT_PRIMARY, hu.tilos.radio.jooqmodel.tables.TagTextcontent.TAG_TEXTCONTENT, hu.tilos.radio.jooqmodel.tables.TagTextcontent.TAG_TEXTCONTENT.TEXTCONTENT_ID);
		public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.TagTextcontentRecord, hu.tilos.radio.jooqmodel.tables.records.TagRecord> FK_EB33439BAD26311 = createForeignKey(hu.tilos.radio.jooqmodel.Keys.KEY_TAG_PRIMARY, hu.tilos.radio.jooqmodel.tables.TagTextcontent.TAG_TEXTCONTENT, hu.tilos.radio.jooqmodel.tables.TagTextcontent.TAG_TEXTCONTENT.TAG_ID);
		public static final org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.UserRecord, hu.tilos.radio.jooqmodel.tables.records.RoleRecord> FK_8D93D649D60322AC = createForeignKey(hu.tilos.radio.jooqmodel.Keys.KEY_ROLE_PRIMARY, hu.tilos.radio.jooqmodel.tables.User.USER, hu.tilos.radio.jooqmodel.tables.User.USER.ROLE_ID);
	}
}
