/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in tilos2
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table tilos2.api_audit
	 */
	public static final hu.tilos.radio.jooqmodel.tables.ApiAudit API_AUDIT = hu.tilos.radio.jooqmodel.tables.ApiAudit.API_AUDIT;

	/**
	 * The table tilos2.audit
	 */
	public static final hu.tilos.radio.jooqmodel.tables.Audit AUDIT = hu.tilos.radio.jooqmodel.tables.Audit.AUDIT;

	/**
	 * The table tilos2.author
	 */
	public static final hu.tilos.radio.jooqmodel.tables.Author AUTHOR = hu.tilos.radio.jooqmodel.tables.Author.AUTHOR;

	/**
	 * The table tilos2.author_url
	 */
	public static final hu.tilos.radio.jooqmodel.tables.AuthorUrl AUTHOR_URL = hu.tilos.radio.jooqmodel.tables.AuthorUrl.AUTHOR_URL;

	/**
	 * The table tilos2.change_password
	 */
	public static final hu.tilos.radio.jooqmodel.tables.ChangePassword CHANGE_PASSWORD = hu.tilos.radio.jooqmodel.tables.ChangePassword.CHANGE_PASSWORD;

	/**
	 * The table tilos2.contribution
	 */
	public static final hu.tilos.radio.jooqmodel.tables.Contribution CONTRIBUTION = hu.tilos.radio.jooqmodel.tables.Contribution.CONTRIBUTION;

	/**
	 * The table tilos2.episode
	 */
	public static final hu.tilos.radio.jooqmodel.tables.Episode EPISODE = hu.tilos.radio.jooqmodel.tables.Episode.EPISODE;

	/**
	 * The table tilos2.listener_stat
	 */
	public static final hu.tilos.radio.jooqmodel.tables.ListenerStat LISTENER_STAT = hu.tilos.radio.jooqmodel.tables.ListenerStat.LISTENER_STAT;

	/**
	 * The table tilos2.migration_versions
	 */
	public static final hu.tilos.radio.jooqmodel.tables.MigrationVersions MIGRATION_VERSIONS = hu.tilos.radio.jooqmodel.tables.MigrationVersions.MIGRATION_VERSIONS;

	/**
	 * The table tilos2.mix
	 */
	public static final hu.tilos.radio.jooqmodel.tables.Mix MIX = hu.tilos.radio.jooqmodel.tables.Mix.MIX;

	/**
	 * The table tilos2.radioshow
	 */
	public static final hu.tilos.radio.jooqmodel.tables.Radioshow RADIOSHOW = hu.tilos.radio.jooqmodel.tables.Radioshow.RADIOSHOW;

	/**
	 * The table tilos2.role
	 */
	public static final hu.tilos.radio.jooqmodel.tables.Role ROLE = hu.tilos.radio.jooqmodel.tables.Role.ROLE;

	/**
	 * The table tilos2.scheduling
	 */
	public static final hu.tilos.radio.jooqmodel.tables.Scheduling SCHEDULING = hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING;

	/**
	 * The table tilos2.show_url
	 */
	public static final hu.tilos.radio.jooqmodel.tables.ShowUrl SHOW_URL = hu.tilos.radio.jooqmodel.tables.ShowUrl.SHOW_URL;

	/**
	 * The table tilos2.tag
	 */
	public static final hu.tilos.radio.jooqmodel.tables.Tag TAG = hu.tilos.radio.jooqmodel.tables.Tag.TAG;

	/**
	 * The table tilos2.tag_textcontent
	 */
	public static final hu.tilos.radio.jooqmodel.tables.TagTextcontent TAG_TEXTCONTENT = hu.tilos.radio.jooqmodel.tables.TagTextcontent.TAG_TEXTCONTENT;

	/**
	 * The table tilos2.textcontent
	 */
	public static final hu.tilos.radio.jooqmodel.tables.Textcontent TEXTCONTENT = hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT;

	/**
	 * The table tilos2.url
	 */
	public static final hu.tilos.radio.jooqmodel.tables.Url URL = hu.tilos.radio.jooqmodel.tables.Url.URL;

	/**
	 * The table tilos2.user
	 */
	public static final hu.tilos.radio.jooqmodel.tables.User USER = hu.tilos.radio.jooqmodel.tables.User.USER;
}
