/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tilos2 extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -2101313076;

	/**
	 * The singleton instance of <code>tilos2</code>
	 */
	public static final Tilos2 TILOS2 = new Tilos2();

	/**
	 * No further instances allowed
	 */
	private Tilos2() {
		super("tilos2");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			hu.tilos.radio.jooqmodel.tables.ApiAudit.API_AUDIT,
			hu.tilos.radio.jooqmodel.tables.Audit.AUDIT,
			hu.tilos.radio.jooqmodel.tables.Author.AUTHOR,
			hu.tilos.radio.jooqmodel.tables.AuthorUrl.AUTHOR_URL,
			hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK,
			hu.tilos.radio.jooqmodel.tables.ChangePassword.CHANGE_PASSWORD,
			hu.tilos.radio.jooqmodel.tables.Contribution.CONTRIBUTION,
			hu.tilos.radio.jooqmodel.tables.Episode.EPISODE,
			hu.tilos.radio.jooqmodel.tables.ListenerStat.LISTENER_STAT,
			hu.tilos.radio.jooqmodel.tables.MigrationVersions.MIGRATION_VERSIONS,
			hu.tilos.radio.jooqmodel.tables.Mix.MIX,
			hu.tilos.radio.jooqmodel.tables.Radioshow.RADIOSHOW,
			hu.tilos.radio.jooqmodel.tables.Role.ROLE,
			hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING,
			hu.tilos.radio.jooqmodel.tables.ShowUrl.SHOW_URL,
			hu.tilos.radio.jooqmodel.tables.Tag.TAG,
			hu.tilos.radio.jooqmodel.tables.TagTextcontent.TAG_TEXTCONTENT,
			hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT,
			hu.tilos.radio.jooqmodel.tables.Url.URL,
			hu.tilos.radio.jooqmodel.tables.User.USER);
	}
}
