<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Tilos Admin v2.0a') ?>

        <?php echo $this->headMeta()
                        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => '/img/favicon.ico'))
                        ->prependStylesheet('/css/admin.css')
                        ->prependStylesheet('/components/bootstrap/dist/css/bootstrap-theme.min.css')
                        ->prependStylesheet('/components/bootstrap/dist/css/bootstrap.min.css') ?>

    </head>
    <body>
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
        
        <!-- Scripts -->
        <?php echo $this->headScript()
                        ->prependFile('/components/bootstrap/dist/js/bootstrap.min.js')
                        ->prependFile('/components/jquery/jquery.min.js')
        ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>