<div>
    <h2>Login</h2>
    <form action="<?= $this->url('auth') ?>" method="POST">
        <label>
            Név:<br />
            <input name="username" type="text" value="" />
        </label>
        <br />
        <label>
            Jelszó:<br />
            <input name="password" type="password" value="" />
        </label>
        <br />
        <input type="submit" value="Belépés" />
    </form>
</div>