/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApiAudit extends org.jooq.impl.TableImpl<hu.tilos.radio.jooqmodel.tables.records.ApiAuditRecord> {

	private static final long serialVersionUID = 1843549417;

	/**
	 * The singleton instance of <code>tilos2.api_audit</code>
	 */
	public static final hu.tilos.radio.jooqmodel.tables.ApiAudit API_AUDIT = new hu.tilos.radio.jooqmodel.tables.ApiAudit();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<hu.tilos.radio.jooqmodel.tables.records.ApiAuditRecord> getRecordType() {
		return hu.tilos.radio.jooqmodel.tables.records.ApiAuditRecord.class;
	}

	/**
	 * The column <code>tilos2.api_audit.id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.ApiAuditRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>tilos2.api_audit.user</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.ApiAuditRecord, java.lang.String> USER = createField("user", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>tilos2.api_audit.url</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.ApiAuditRecord, java.lang.String> URL = createField("url", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false), this, "");

	/**
	 * The column <code>tilos2.api_audit.postParams</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.ApiAuditRecord, java.lang.String> POSTPARAMS = createField("postParams", org.jooq.impl.SQLDataType.VARCHAR.length(500).nullable(false), this, "");

	/**
	 * The column <code>tilos2.api_audit.callDate</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.ApiAuditRecord, java.sql.Timestamp> CALLDATE = createField("callDate", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>tilos2.api_audit.method</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.ApiAuditRecord, java.lang.String> METHOD = createField("method", org.jooq.impl.SQLDataType.VARCHAR.length(10).nullable(false), this, "");

	/**
	 * Create a <code>tilos2.api_audit</code> table reference
	 */
	public ApiAudit() {
		this("api_audit", null);
	}

	/**
	 * Create an aliased <code>tilos2.api_audit</code> table reference
	 */
	public ApiAudit(java.lang.String alias) {
		this(alias, hu.tilos.radio.jooqmodel.tables.ApiAudit.API_AUDIT);
	}

	private ApiAudit(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.ApiAuditRecord> aliased) {
		this(alias, aliased, null);
	}

	private ApiAudit(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.ApiAuditRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, hu.tilos.radio.jooqmodel.Tilos2.TILOS2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.ApiAuditRecord, java.lang.Integer> getIdentity() {
		return hu.tilos.radio.jooqmodel.Keys.IDENTITY_API_AUDIT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ApiAuditRecord> getPrimaryKey() {
		return hu.tilos.radio.jooqmodel.Keys.KEY_API_AUDIT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ApiAuditRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ApiAuditRecord>>asList(hu.tilos.radio.jooqmodel.Keys.KEY_API_AUDIT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public hu.tilos.radio.jooqmodel.tables.ApiAudit as(java.lang.String alias) {
		return new hu.tilos.radio.jooqmodel.tables.ApiAudit(alias, this);
	}

	/**
	 * Rename this table
	 */
	public hu.tilos.radio.jooqmodel.tables.ApiAudit rename(java.lang.String name) {
		return new hu.tilos.radio.jooqmodel.tables.ApiAudit(name, null);
	}
}
