/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Author extends org.jooq.impl.TableImpl<hu.tilos.radio.jooqmodel.tables.records.AuthorRecord> {

	private static final long serialVersionUID = 2074638467;

	/**
	 * The singleton instance of <code>tilos2.author</code>
	 */
	public static final hu.tilos.radio.jooqmodel.tables.Author AUTHOR = new hu.tilos.radio.jooqmodel.tables.Author();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<hu.tilos.radio.jooqmodel.tables.records.AuthorRecord> getRecordType() {
		return hu.tilos.radio.jooqmodel.tables.records.AuthorRecord.class;
	}

	/**
	 * The column <code>tilos2.author.id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.AuthorRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>tilos2.author.user_id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.AuthorRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>tilos2.author.name</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.AuthorRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>tilos2.author.alias</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.AuthorRecord, java.lang.String> ALIAS = createField("alias", org.jooq.impl.SQLDataType.VARCHAR.length(40), this, "");

	/**
	 * The column <code>tilos2.author.photo</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.AuthorRecord, java.lang.String> PHOTO = createField("photo", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>tilos2.author.avatar</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.AuthorRecord, java.lang.String> AVATAR = createField("avatar", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>tilos2.author.introduction</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.AuthorRecord, java.lang.String> INTRODUCTION = createField("introduction", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>tilos2.author.email</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.AuthorRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>tilos2.author</code> table reference
	 */
	public Author() {
		this("author", null);
	}

	/**
	 * Create an aliased <code>tilos2.author</code> table reference
	 */
	public Author(java.lang.String alias) {
		this(alias, hu.tilos.radio.jooqmodel.tables.Author.AUTHOR);
	}

	private Author(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.AuthorRecord> aliased) {
		this(alias, aliased, null);
	}

	private Author(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.AuthorRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, hu.tilos.radio.jooqmodel.Tilos2.TILOS2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.AuthorRecord, java.lang.Integer> getIdentity() {
		return hu.tilos.radio.jooqmodel.Keys.IDENTITY_AUTHOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.AuthorRecord> getPrimaryKey() {
		return hu.tilos.radio.jooqmodel.Keys.KEY_AUTHOR_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.AuthorRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.AuthorRecord>>asList(hu.tilos.radio.jooqmodel.Keys.KEY_AUTHOR_PRIMARY, hu.tilos.radio.jooqmodel.Keys.KEY_AUTHOR_UNIQ_BDAFD8C8A76ED395);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.AuthorRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.AuthorRecord, ?>>asList(hu.tilos.radio.jooqmodel.Keys.FK_BDAFD8C8A76ED395);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public hu.tilos.radio.jooqmodel.tables.Author as(java.lang.String alias) {
		return new hu.tilos.radio.jooqmodel.tables.Author(alias, this);
	}

	/**
	 * Rename this table
	 */
	public hu.tilos.radio.jooqmodel.tables.Author rename(java.lang.String name) {
		return new hu.tilos.radio.jooqmodel.tables.Author(name, null);
	}
}
