/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorUrl extends org.jooq.impl.TableImpl<hu.tilos.radio.jooqmodel.tables.records.AuthorUrlRecord> {

	private static final long serialVersionUID = -2113293758;

	/**
	 * The singleton instance of <code>tilos2.author_url</code>
	 */
	public static final hu.tilos.radio.jooqmodel.tables.AuthorUrl AUTHOR_URL = new hu.tilos.radio.jooqmodel.tables.AuthorUrl();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<hu.tilos.radio.jooqmodel.tables.records.AuthorUrlRecord> getRecordType() {
		return hu.tilos.radio.jooqmodel.tables.records.AuthorUrlRecord.class;
	}

	/**
	 * The column <code>tilos2.author_url.author_id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.AuthorUrlRecord, java.lang.Integer> AUTHOR_ID = createField("author_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>tilos2.author_url.url_id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.AuthorUrlRecord, java.lang.Integer> URL_ID = createField("url_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>tilos2.author_url</code> table reference
	 */
	public AuthorUrl() {
		this("author_url", null);
	}

	/**
	 * Create an aliased <code>tilos2.author_url</code> table reference
	 */
	public AuthorUrl(java.lang.String alias) {
		this(alias, hu.tilos.radio.jooqmodel.tables.AuthorUrl.AUTHOR_URL);
	}

	private AuthorUrl(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.AuthorUrlRecord> aliased) {
		this(alias, aliased, null);
	}

	private AuthorUrl(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.AuthorUrlRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, hu.tilos.radio.jooqmodel.Tilos2.TILOS2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.AuthorUrlRecord> getPrimaryKey() {
		return hu.tilos.radio.jooqmodel.Keys.KEY_AUTHOR_URL_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.AuthorUrlRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.AuthorUrlRecord>>asList(hu.tilos.radio.jooqmodel.Keys.KEY_AUTHOR_URL_PRIMARY, hu.tilos.radio.jooqmodel.Keys.KEY_AUTHOR_URL_UNIQ_1531912281CFDAE7);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.AuthorUrlRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.AuthorUrlRecord, ?>>asList(hu.tilos.radio.jooqmodel.Keys.FK_15319122F675F31B, hu.tilos.radio.jooqmodel.Keys.FK_1531912281CFDAE7);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public hu.tilos.radio.jooqmodel.tables.AuthorUrl as(java.lang.String alias) {
		return new hu.tilos.radio.jooqmodel.tables.AuthorUrl(alias, this);
	}

	/**
	 * Rename this table
	 */
	public hu.tilos.radio.jooqmodel.tables.AuthorUrl rename(java.lang.String name) {
		return new hu.tilos.radio.jooqmodel.tables.AuthorUrl(name, null);
	}
}
