/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bookmark extends org.jooq.impl.TableImpl<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord> {

	private static final long serialVersionUID = -44839615;

	/**
	 * The singleton instance of <code>tilos2.bookmark</code>
	 */
	public static final hu.tilos.radio.jooqmodel.tables.Bookmark BOOKMARK = new hu.tilos.radio.jooqmodel.tables.Bookmark();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord> getRecordType() {
		return hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord.class;
	}

	/**
	 * The column <code>tilos2.bookmark.id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>tilos2.bookmark.radioshow_id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord, java.lang.Integer> RADIOSHOW_ID = createField("radioshow_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>tilos2.bookmark.episode_id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord, java.lang.Integer> EPISODE_ID = createField("episode_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>tilos2.bookmark.user_id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>tilos2.bookmark.modified</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord, java.sql.Timestamp> MODIFIED = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>tilos2.bookmark.title</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(160).nullable(false), this, "");

	/**
	 * The column <code>tilos2.bookmark.content</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord, java.lang.String> CONTENT = createField("content", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>tilos2.bookmark.start</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord, java.sql.Timestamp> START = createField("start", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>tilos2.bookmark.end</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord, java.sql.Timestamp> END = createField("end", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * Create a <code>tilos2.bookmark</code> table reference
	 */
	public Bookmark() {
		this("bookmark", null);
	}

	/**
	 * Create an aliased <code>tilos2.bookmark</code> table reference
	 */
	public Bookmark(java.lang.String alias) {
		this(alias, hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK);
	}

	private Bookmark(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord> aliased) {
		this(alias, aliased, null);
	}

	private Bookmark(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, hu.tilos.radio.jooqmodel.Tilos2.TILOS2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord, java.lang.Integer> getIdentity() {
		return hu.tilos.radio.jooqmodel.Keys.IDENTITY_BOOKMARK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord> getPrimaryKey() {
		return hu.tilos.radio.jooqmodel.Keys.KEY_BOOKMARK_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord>>asList(hu.tilos.radio.jooqmodel.Keys.KEY_BOOKMARK_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord, ?>>asList(hu.tilos.radio.jooqmodel.Keys.FK_DA62921D4E549204, hu.tilos.radio.jooqmodel.Keys.FK_DA62921D362B62A0, hu.tilos.radio.jooqmodel.Keys.FK_DA62921DA76ED395);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public hu.tilos.radio.jooqmodel.tables.Bookmark as(java.lang.String alias) {
		return new hu.tilos.radio.jooqmodel.tables.Bookmark(alias, this);
	}

	/**
	 * Rename this table
	 */
	public hu.tilos.radio.jooqmodel.tables.Bookmark rename(java.lang.String name) {
		return new hu.tilos.radio.jooqmodel.tables.Bookmark(name, null);
	}
}
