/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChangePassword extends org.jooq.impl.TableImpl<hu.tilos.radio.jooqmodel.tables.records.ChangePasswordRecord> {

	private static final long serialVersionUID = 980163408;

	/**
	 * The singleton instance of <code>tilos2.change_password</code>
	 */
	public static final hu.tilos.radio.jooqmodel.tables.ChangePassword CHANGE_PASSWORD = new hu.tilos.radio.jooqmodel.tables.ChangePassword();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<hu.tilos.radio.jooqmodel.tables.records.ChangePasswordRecord> getRecordType() {
		return hu.tilos.radio.jooqmodel.tables.records.ChangePasswordRecord.class;
	}

	/**
	 * The column <code>tilos2.change_password.id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.ChangePasswordRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>tilos2.change_password.user_id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.ChangePasswordRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>tilos2.change_password.token</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.ChangePasswordRecord, java.lang.String> TOKEN = createField("token", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false), this, "");

	/**
	 * The column <code>tilos2.change_password.created</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.ChangePasswordRecord, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * Create a <code>tilos2.change_password</code> table reference
	 */
	public ChangePassword() {
		this("change_password", null);
	}

	/**
	 * Create an aliased <code>tilos2.change_password</code> table reference
	 */
	public ChangePassword(java.lang.String alias) {
		this(alias, hu.tilos.radio.jooqmodel.tables.ChangePassword.CHANGE_PASSWORD);
	}

	private ChangePassword(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.ChangePasswordRecord> aliased) {
		this(alias, aliased, null);
	}

	private ChangePassword(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.ChangePasswordRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, hu.tilos.radio.jooqmodel.Tilos2.TILOS2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.ChangePasswordRecord, java.lang.Integer> getIdentity() {
		return hu.tilos.radio.jooqmodel.Keys.IDENTITY_CHANGE_PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ChangePasswordRecord> getPrimaryKey() {
		return hu.tilos.radio.jooqmodel.Keys.KEY_CHANGE_PASSWORD_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ChangePasswordRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ChangePasswordRecord>>asList(hu.tilos.radio.jooqmodel.Keys.KEY_CHANGE_PASSWORD_PRIMARY, hu.tilos.radio.jooqmodel.Keys.KEY_CHANGE_PASSWORD_UNIQ_9A385A3BA76ED395);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.ChangePasswordRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.ChangePasswordRecord, ?>>asList(hu.tilos.radio.jooqmodel.Keys.FK_9A385A3BA76ED395);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public hu.tilos.radio.jooqmodel.tables.ChangePassword as(java.lang.String alias) {
		return new hu.tilos.radio.jooqmodel.tables.ChangePassword(alias, this);
	}

	/**
	 * Rename this table
	 */
	public hu.tilos.radio.jooqmodel.tables.ChangePassword rename(java.lang.String name) {
		return new hu.tilos.radio.jooqmodel.tables.ChangePassword(name, null);
	}
}
