/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Contribution extends org.jooq.impl.TableImpl<hu.tilos.radio.jooqmodel.tables.records.ContributionRecord> {

	private static final long serialVersionUID = -527089935;

	/**
	 * The singleton instance of <code>tilos2.contribution</code>
	 */
	public static final hu.tilos.radio.jooqmodel.tables.Contribution CONTRIBUTION = new hu.tilos.radio.jooqmodel.tables.Contribution();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<hu.tilos.radio.jooqmodel.tables.records.ContributionRecord> getRecordType() {
		return hu.tilos.radio.jooqmodel.tables.records.ContributionRecord.class;
	}

	/**
	 * The column <code>tilos2.contribution.id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.ContributionRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>tilos2.contribution.radioshow_id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.ContributionRecord, java.lang.Integer> RADIOSHOW_ID = createField("radioshow_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>tilos2.contribution.author_id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.ContributionRecord, java.lang.Integer> AUTHOR_ID = createField("author_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>tilos2.contribution.nick</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.ContributionRecord, java.lang.String> NICK = createField("nick", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * Create a <code>tilos2.contribution</code> table reference
	 */
	public Contribution() {
		this("contribution", null);
	}

	/**
	 * Create an aliased <code>tilos2.contribution</code> table reference
	 */
	public Contribution(java.lang.String alias) {
		this(alias, hu.tilos.radio.jooqmodel.tables.Contribution.CONTRIBUTION);
	}

	private Contribution(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.ContributionRecord> aliased) {
		this(alias, aliased, null);
	}

	private Contribution(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.ContributionRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, hu.tilos.radio.jooqmodel.Tilos2.TILOS2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.ContributionRecord, java.lang.Integer> getIdentity() {
		return hu.tilos.radio.jooqmodel.Keys.IDENTITY_CONTRIBUTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ContributionRecord> getPrimaryKey() {
		return hu.tilos.radio.jooqmodel.Keys.KEY_CONTRIBUTION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ContributionRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ContributionRecord>>asList(hu.tilos.radio.jooqmodel.Keys.KEY_CONTRIBUTION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.ContributionRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.ContributionRecord, ?>>asList(hu.tilos.radio.jooqmodel.Keys.FK_EA351E154E549204, hu.tilos.radio.jooqmodel.Keys.FK_EA351E15F675F31B);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public hu.tilos.radio.jooqmodel.tables.Contribution as(java.lang.String alias) {
		return new hu.tilos.radio.jooqmodel.tables.Contribution(alias, this);
	}

	/**
	 * Rename this table
	 */
	public hu.tilos.radio.jooqmodel.tables.Contribution rename(java.lang.String name) {
		return new hu.tilos.radio.jooqmodel.tables.Contribution(name, null);
	}
}
