/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Episode extends org.jooq.impl.TableImpl<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord> {

	private static final long serialVersionUID = 19634924;

	/**
	 * The singleton instance of <code>tilos2.episode</code>
	 */
	public static final hu.tilos.radio.jooqmodel.tables.Episode EPISODE = new hu.tilos.radio.jooqmodel.tables.Episode();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord> getRecordType() {
		return hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord.class;
	}

	/**
	 * The column <code>tilos2.episode.id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>tilos2.episode.radioshow_id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord, java.lang.Integer> RADIOSHOW_ID = createField("radioshow_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>tilos2.episode.textcontent_id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord, java.lang.Integer> TEXTCONTENT_ID = createField("textcontent_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>tilos2.episode.plannedFrom</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord, java.sql.Timestamp> PLANNEDFROM = createField("plannedFrom", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>tilos2.episode.plannedTo</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord, java.sql.Timestamp> PLANNEDTO = createField("plannedTo", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>tilos2.episode.realFrom</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord, java.sql.Timestamp> REALFROM = createField("realFrom", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>tilos2.episode.realTo</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord, java.sql.Timestamp> REALTO = createField("realTo", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * Create a <code>tilos2.episode</code> table reference
	 */
	public Episode() {
		this("episode", null);
	}

	/**
	 * Create an aliased <code>tilos2.episode</code> table reference
	 */
	public Episode(java.lang.String alias) {
		this(alias, hu.tilos.radio.jooqmodel.tables.Episode.EPISODE);
	}

	private Episode(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord> aliased) {
		this(alias, aliased, null);
	}

	private Episode(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, hu.tilos.radio.jooqmodel.Tilos2.TILOS2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord, java.lang.Integer> getIdentity() {
		return hu.tilos.radio.jooqmodel.Keys.IDENTITY_EPISODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord> getPrimaryKey() {
		return hu.tilos.radio.jooqmodel.Keys.KEY_EPISODE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord>>asList(hu.tilos.radio.jooqmodel.Keys.KEY_EPISODE_PRIMARY, hu.tilos.radio.jooqmodel.Keys.KEY_EPISODE_UNIQ_DDAA1CDA3A333134);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord, ?>>asList(hu.tilos.radio.jooqmodel.Keys.FK_DDAA1CDA4E549204, hu.tilos.radio.jooqmodel.Keys.FK_DDAA1CDA3A333134);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public hu.tilos.radio.jooqmodel.tables.Episode as(java.lang.String alias) {
		return new hu.tilos.radio.jooqmodel.tables.Episode(alias, this);
	}

	/**
	 * Rename this table
	 */
	public hu.tilos.radio.jooqmodel.tables.Episode rename(java.lang.String name) {
		return new hu.tilos.radio.jooqmodel.tables.Episode(name, null);
	}
}
