/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ListenerStat extends org.jooq.impl.TableImpl<hu.tilos.radio.jooqmodel.tables.records.ListenerStatRecord> {

	private static final long serialVersionUID = 430609064;

	/**
	 * The singleton instance of <code>tilos2.listener_stat</code>
	 */
	public static final hu.tilos.radio.jooqmodel.tables.ListenerStat LISTENER_STAT = new hu.tilos.radio.jooqmodel.tables.ListenerStat();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<hu.tilos.radio.jooqmodel.tables.records.ListenerStatRecord> getRecordType() {
		return hu.tilos.radio.jooqmodel.tables.records.ListenerStatRecord.class;
	}

	/**
	 * The column <code>tilos2.listener_stat.id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.ListenerStatRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>tilos2.listener_stat.type</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.ListenerStatRecord, java.lang.Integer> TYPE = createField("type", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>tilos2.listener_stat.count</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.ListenerStatRecord, java.lang.Integer> COUNT = createField("count", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>tilos2.listener_stat.date</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.ListenerStatRecord, java.sql.Timestamp> DATE = createField("date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * Create a <code>tilos2.listener_stat</code> table reference
	 */
	public ListenerStat() {
		this("listener_stat", null);
	}

	/**
	 * Create an aliased <code>tilos2.listener_stat</code> table reference
	 */
	public ListenerStat(java.lang.String alias) {
		this(alias, hu.tilos.radio.jooqmodel.tables.ListenerStat.LISTENER_STAT);
	}

	private ListenerStat(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.ListenerStatRecord> aliased) {
		this(alias, aliased, null);
	}

	private ListenerStat(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.ListenerStatRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, hu.tilos.radio.jooqmodel.Tilos2.TILOS2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.ListenerStatRecord, java.lang.Integer> getIdentity() {
		return hu.tilos.radio.jooqmodel.Keys.IDENTITY_LISTENER_STAT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ListenerStatRecord> getPrimaryKey() {
		return hu.tilos.radio.jooqmodel.Keys.KEY_LISTENER_STAT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ListenerStatRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ListenerStatRecord>>asList(hu.tilos.radio.jooqmodel.Keys.KEY_LISTENER_STAT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public hu.tilos.radio.jooqmodel.tables.ListenerStat as(java.lang.String alias) {
		return new hu.tilos.radio.jooqmodel.tables.ListenerStat(alias, this);
	}

	/**
	 * Rename this table
	 */
	public hu.tilos.radio.jooqmodel.tables.ListenerStat rename(java.lang.String name) {
		return new hu.tilos.radio.jooqmodel.tables.ListenerStat(name, null);
	}
}
