/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MigrationVersions extends org.jooq.impl.TableImpl<hu.tilos.radio.jooqmodel.tables.records.MigrationVersionsRecord> {

	private static final long serialVersionUID = -435898033;

	/**
	 * The singleton instance of <code>tilos2.migration_versions</code>
	 */
	public static final hu.tilos.radio.jooqmodel.tables.MigrationVersions MIGRATION_VERSIONS = new hu.tilos.radio.jooqmodel.tables.MigrationVersions();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<hu.tilos.radio.jooqmodel.tables.records.MigrationVersionsRecord> getRecordType() {
		return hu.tilos.radio.jooqmodel.tables.records.MigrationVersionsRecord.class;
	}

	/**
	 * The column <code>tilos2.migration_versions.version</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.MigrationVersionsRecord, java.lang.String> VERSION = createField("version", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>tilos2.migration_versions</code> table reference
	 */
	public MigrationVersions() {
		this("migration_versions", null);
	}

	/**
	 * Create an aliased <code>tilos2.migration_versions</code> table reference
	 */
	public MigrationVersions(java.lang.String alias) {
		this(alias, hu.tilos.radio.jooqmodel.tables.MigrationVersions.MIGRATION_VERSIONS);
	}

	private MigrationVersions(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.MigrationVersionsRecord> aliased) {
		this(alias, aliased, null);
	}

	private MigrationVersions(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.MigrationVersionsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, hu.tilos.radio.jooqmodel.Tilos2.TILOS2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.MigrationVersionsRecord> getPrimaryKey() {
		return hu.tilos.radio.jooqmodel.Keys.KEY_MIGRATION_VERSIONS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.MigrationVersionsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.MigrationVersionsRecord>>asList(hu.tilos.radio.jooqmodel.Keys.KEY_MIGRATION_VERSIONS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public hu.tilos.radio.jooqmodel.tables.MigrationVersions as(java.lang.String alias) {
		return new hu.tilos.radio.jooqmodel.tables.MigrationVersions(alias, this);
	}

	/**
	 * Rename this table
	 */
	public hu.tilos.radio.jooqmodel.tables.MigrationVersions rename(java.lang.String name) {
		return new hu.tilos.radio.jooqmodel.tables.MigrationVersions(name, null);
	}
}
