/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mix extends org.jooq.impl.TableImpl<hu.tilos.radio.jooqmodel.tables.records.MixRecord> {

	private static final long serialVersionUID = -1263332002;

	/**
	 * The singleton instance of <code>tilos2.mix</code>
	 */
	public static final hu.tilos.radio.jooqmodel.tables.Mix MIX = new hu.tilos.radio.jooqmodel.tables.Mix();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<hu.tilos.radio.jooqmodel.tables.records.MixRecord> getRecordType() {
		return hu.tilos.radio.jooqmodel.tables.records.MixRecord.class;
	}

	/**
	 * The column <code>tilos2.mix.id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.MixRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>tilos2.mix.show_id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.MixRecord, java.lang.Integer> SHOW_ID = createField("show_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>tilos2.mix.author</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.MixRecord, java.lang.String> AUTHOR = createField("author", org.jooq.impl.SQLDataType.VARCHAR.length(40), this, "");

	/**
	 * The column <code>tilos2.mix.title</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.MixRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false), this, "");

	/**
	 * The column <code>tilos2.mix.file</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.MixRecord, java.lang.String> FILE = createField("file", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>tilos2.mix.date</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.MixRecord, java.sql.Date> DATE = createField("date", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>tilos2.mix.type</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.MixRecord, java.lang.Integer> TYPE = createField("type", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>tilos2.mix</code> table reference
	 */
	public Mix() {
		this("mix", null);
	}

	/**
	 * Create an aliased <code>tilos2.mix</code> table reference
	 */
	public Mix(java.lang.String alias) {
		this(alias, hu.tilos.radio.jooqmodel.tables.Mix.MIX);
	}

	private Mix(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.MixRecord> aliased) {
		this(alias, aliased, null);
	}

	private Mix(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.MixRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, hu.tilos.radio.jooqmodel.Tilos2.TILOS2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.MixRecord, java.lang.Integer> getIdentity() {
		return hu.tilos.radio.jooqmodel.Keys.IDENTITY_MIX;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.MixRecord> getPrimaryKey() {
		return hu.tilos.radio.jooqmodel.Keys.KEY_MIX_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.MixRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.MixRecord>>asList(hu.tilos.radio.jooqmodel.Keys.KEY_MIX_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.MixRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.MixRecord, ?>>asList(hu.tilos.radio.jooqmodel.Keys.FK_55AFA881D0C1FC64);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public hu.tilos.radio.jooqmodel.tables.Mix as(java.lang.String alias) {
		return new hu.tilos.radio.jooqmodel.tables.Mix(alias, this);
	}

	/**
	 * Rename this table
	 */
	public hu.tilos.radio.jooqmodel.tables.Mix rename(java.lang.String name) {
		return new hu.tilos.radio.jooqmodel.tables.Mix(name, null);
	}
}
