/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Radioshow extends org.jooq.impl.TableImpl<hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord> {

	private static final long serialVersionUID = -103787728;

	/**
	 * The singleton instance of <code>tilos2.radioshow</code>
	 */
	public static final hu.tilos.radio.jooqmodel.tables.Radioshow RADIOSHOW = new hu.tilos.radio.jooqmodel.tables.Radioshow();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord> getRecordType() {
		return hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord.class;
	}

	/**
	 * The column <code>tilos2.radioshow.id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>tilos2.radioshow.name</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>tilos2.radioshow.definition</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord, java.lang.String> DEFINITION = createField("definition", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>tilos2.radioshow.alias</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord, java.lang.String> ALIAS = createField("alias", org.jooq.impl.SQLDataType.VARCHAR.length(60), this, "");

	/**
	 * The column <code>tilos2.radioshow.banner</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord, java.lang.String> BANNER = createField("banner", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>tilos2.radioshow.description</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>tilos2.radioshow.type</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord, java.lang.Integer> TYPE = createField("type", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>tilos2.radioshow.status</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord, java.lang.Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>tilos2.radioshow</code> table reference
	 */
	public Radioshow() {
		this("radioshow", null);
	}

	/**
	 * Create an aliased <code>tilos2.radioshow</code> table reference
	 */
	public Radioshow(java.lang.String alias) {
		this(alias, hu.tilos.radio.jooqmodel.tables.Radioshow.RADIOSHOW);
	}

	private Radioshow(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord> aliased) {
		this(alias, aliased, null);
	}

	private Radioshow(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, hu.tilos.radio.jooqmodel.Tilos2.TILOS2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord, java.lang.Integer> getIdentity() {
		return hu.tilos.radio.jooqmodel.Keys.IDENTITY_RADIOSHOW;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord> getPrimaryKey() {
		return hu.tilos.radio.jooqmodel.Keys.KEY_RADIOSHOW_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord>>asList(hu.tilos.radio.jooqmodel.Keys.KEY_RADIOSHOW_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public hu.tilos.radio.jooqmodel.tables.Radioshow as(java.lang.String alias) {
		return new hu.tilos.radio.jooqmodel.tables.Radioshow(alias, this);
	}

	/**
	 * Rename this table
	 */
	public hu.tilos.radio.jooqmodel.tables.Radioshow rename(java.lang.String name) {
		return new hu.tilos.radio.jooqmodel.tables.Radioshow(name, null);
	}
}
