/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Scheduling extends org.jooq.impl.TableImpl<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord> {

	private static final long serialVersionUID = 218648537;

	/**
	 * The singleton instance of <code>tilos2.scheduling</code>
	 */
	public static final hu.tilos.radio.jooqmodel.tables.Scheduling SCHEDULING = new hu.tilos.radio.jooqmodel.tables.Scheduling();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord> getRecordType() {
		return hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord.class;
	}

	/**
	 * The column <code>tilos2.scheduling.id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>tilos2.scheduling.radioshow_id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord, java.lang.Integer> RADIOSHOW_ID = createField("radioshow_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>tilos2.scheduling.weekType</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord, java.lang.Short> WEEKTYPE = createField("weekType", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>tilos2.scheduling.base</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord, java.sql.Date> BASE = createField("base", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

	/**
	 * The column <code>tilos2.scheduling.weekDay</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord, java.lang.Short> WEEKDAY = createField("weekDay", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>tilos2.scheduling.hourFrom</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord, java.lang.Short> HOURFROM = createField("hourFrom", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>tilos2.scheduling.minFrom</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord, java.lang.Short> MINFROM = createField("minFrom", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>tilos2.scheduling.duration</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord, java.lang.Short> DURATION = createField("duration", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>tilos2.scheduling.validFrom</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord, java.sql.Date> VALIDFROM = createField("validFrom", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

	/**
	 * The column <code>tilos2.scheduling.validTo</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord, java.sql.Date> VALIDTO = createField("validTo", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

	/**
	 * Create a <code>tilos2.scheduling</code> table reference
	 */
	public Scheduling() {
		this("scheduling", null);
	}

	/**
	 * Create an aliased <code>tilos2.scheduling</code> table reference
	 */
	public Scheduling(java.lang.String alias) {
		this(alias, hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING);
	}

	private Scheduling(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord> aliased) {
		this(alias, aliased, null);
	}

	private Scheduling(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, hu.tilos.radio.jooqmodel.Tilos2.TILOS2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord, java.lang.Integer> getIdentity() {
		return hu.tilos.radio.jooqmodel.Keys.IDENTITY_SCHEDULING;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord> getPrimaryKey() {
		return hu.tilos.radio.jooqmodel.Keys.KEY_SCHEDULING_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord>>asList(hu.tilos.radio.jooqmodel.Keys.KEY_SCHEDULING_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord, ?>>asList(hu.tilos.radio.jooqmodel.Keys.FK_FD931BF54E549204);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public hu.tilos.radio.jooqmodel.tables.Scheduling as(java.lang.String alias) {
		return new hu.tilos.radio.jooqmodel.tables.Scheduling(alias, this);
	}

	/**
	 * Rename this table
	 */
	public hu.tilos.radio.jooqmodel.tables.Scheduling rename(java.lang.String name) {
		return new hu.tilos.radio.jooqmodel.tables.Scheduling(name, null);
	}
}
