/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShowUrl extends org.jooq.impl.TableImpl<hu.tilos.radio.jooqmodel.tables.records.ShowUrlRecord> {

	private static final long serialVersionUID = -1117866849;

	/**
	 * The singleton instance of <code>tilos2.show_url</code>
	 */
	public static final hu.tilos.radio.jooqmodel.tables.ShowUrl SHOW_URL = new hu.tilos.radio.jooqmodel.tables.ShowUrl();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<hu.tilos.radio.jooqmodel.tables.records.ShowUrlRecord> getRecordType() {
		return hu.tilos.radio.jooqmodel.tables.records.ShowUrlRecord.class;
	}

	/**
	 * The column <code>tilos2.show_url.radioshow_id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.ShowUrlRecord, java.lang.Integer> RADIOSHOW_ID = createField("radioshow_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>tilos2.show_url.url_id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.ShowUrlRecord, java.lang.Integer> URL_ID = createField("url_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>tilos2.show_url</code> table reference
	 */
	public ShowUrl() {
		this("show_url", null);
	}

	/**
	 * Create an aliased <code>tilos2.show_url</code> table reference
	 */
	public ShowUrl(java.lang.String alias) {
		this(alias, hu.tilos.radio.jooqmodel.tables.ShowUrl.SHOW_URL);
	}

	private ShowUrl(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.ShowUrlRecord> aliased) {
		this(alias, aliased, null);
	}

	private ShowUrl(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.ShowUrlRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, hu.tilos.radio.jooqmodel.Tilos2.TILOS2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ShowUrlRecord> getPrimaryKey() {
		return hu.tilos.radio.jooqmodel.Keys.KEY_SHOW_URL_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ShowUrlRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.ShowUrlRecord>>asList(hu.tilos.radio.jooqmodel.Keys.KEY_SHOW_URL_PRIMARY, hu.tilos.radio.jooqmodel.Keys.KEY_SHOW_URL_UNIQ_D5AD498081CFDAE7);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.ShowUrlRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.ShowUrlRecord, ?>>asList(hu.tilos.radio.jooqmodel.Keys.FK_D5AD49804E549204, hu.tilos.radio.jooqmodel.Keys.FK_D5AD498081CFDAE7);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public hu.tilos.radio.jooqmodel.tables.ShowUrl as(java.lang.String alias) {
		return new hu.tilos.radio.jooqmodel.tables.ShowUrl(alias, this);
	}

	/**
	 * Rename this table
	 */
	public hu.tilos.radio.jooqmodel.tables.ShowUrl rename(java.lang.String name) {
		return new hu.tilos.radio.jooqmodel.tables.ShowUrl(name, null);
	}
}
