/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tag extends org.jooq.impl.TableImpl<hu.tilos.radio.jooqmodel.tables.records.TagRecord> {

	private static final long serialVersionUID = 1750776414;

	/**
	 * The singleton instance of <code>tilos2.tag</code>
	 */
	public static final hu.tilos.radio.jooqmodel.tables.Tag TAG = new hu.tilos.radio.jooqmodel.tables.Tag();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<hu.tilos.radio.jooqmodel.tables.records.TagRecord> getRecordType() {
		return hu.tilos.radio.jooqmodel.tables.records.TagRecord.class;
	}

	/**
	 * The column <code>tilos2.tag.id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.TagRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>tilos2.tag.name</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.TagRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>tilos2.tag.type</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.TagRecord, java.lang.Integer> TYPE = createField("type", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>tilos2.tag</code> table reference
	 */
	public Tag() {
		this("tag", null);
	}

	/**
	 * Create an aliased <code>tilos2.tag</code> table reference
	 */
	public Tag(java.lang.String alias) {
		this(alias, hu.tilos.radio.jooqmodel.tables.Tag.TAG);
	}

	private Tag(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.TagRecord> aliased) {
		this(alias, aliased, null);
	}

	private Tag(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.TagRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, hu.tilos.radio.jooqmodel.Tilos2.TILOS2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.TagRecord, java.lang.Integer> getIdentity() {
		return hu.tilos.radio.jooqmodel.Keys.IDENTITY_TAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.TagRecord> getPrimaryKey() {
		return hu.tilos.radio.jooqmodel.Keys.KEY_TAG_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.TagRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.TagRecord>>asList(hu.tilos.radio.jooqmodel.Keys.KEY_TAG_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public hu.tilos.radio.jooqmodel.tables.Tag as(java.lang.String alias) {
		return new hu.tilos.radio.jooqmodel.tables.Tag(alias, this);
	}

	/**
	 * Rename this table
	 */
	public hu.tilos.radio.jooqmodel.tables.Tag rename(java.lang.String name) {
		return new hu.tilos.radio.jooqmodel.tables.Tag(name, null);
	}
}
