/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagTextcontent extends org.jooq.impl.TableImpl<hu.tilos.radio.jooqmodel.tables.records.TagTextcontentRecord> {

	private static final long serialVersionUID = 1113821388;

	/**
	 * The singleton instance of <code>tilos2.tag_textcontent</code>
	 */
	public static final hu.tilos.radio.jooqmodel.tables.TagTextcontent TAG_TEXTCONTENT = new hu.tilos.radio.jooqmodel.tables.TagTextcontent();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<hu.tilos.radio.jooqmodel.tables.records.TagTextcontentRecord> getRecordType() {
		return hu.tilos.radio.jooqmodel.tables.records.TagTextcontentRecord.class;
	}

	/**
	 * The column <code>tilos2.tag_textcontent.textcontent_id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.TagTextcontentRecord, java.lang.Integer> TEXTCONTENT_ID = createField("textcontent_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>tilos2.tag_textcontent.tag_id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.TagTextcontentRecord, java.lang.Integer> TAG_ID = createField("tag_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>tilos2.tag_textcontent</code> table reference
	 */
	public TagTextcontent() {
		this("tag_textcontent", null);
	}

	/**
	 * Create an aliased <code>tilos2.tag_textcontent</code> table reference
	 */
	public TagTextcontent(java.lang.String alias) {
		this(alias, hu.tilos.radio.jooqmodel.tables.TagTextcontent.TAG_TEXTCONTENT);
	}

	private TagTextcontent(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.TagTextcontentRecord> aliased) {
		this(alias, aliased, null);
	}

	private TagTextcontent(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.TagTextcontentRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, hu.tilos.radio.jooqmodel.Tilos2.TILOS2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.TagTextcontentRecord> getPrimaryKey() {
		return hu.tilos.radio.jooqmodel.Keys.KEY_TAG_TEXTCONTENT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.TagTextcontentRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.TagTextcontentRecord>>asList(hu.tilos.radio.jooqmodel.Keys.KEY_TAG_TEXTCONTENT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.TagTextcontentRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.TagTextcontentRecord, ?>>asList(hu.tilos.radio.jooqmodel.Keys.FK_EB334393A333134, hu.tilos.radio.jooqmodel.Keys.FK_EB33439BAD26311);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public hu.tilos.radio.jooqmodel.tables.TagTextcontent as(java.lang.String alias) {
		return new hu.tilos.radio.jooqmodel.tables.TagTextcontent(alias, this);
	}

	/**
	 * Rename this table
	 */
	public hu.tilos.radio.jooqmodel.tables.TagTextcontent rename(java.lang.String name) {
		return new hu.tilos.radio.jooqmodel.tables.TagTextcontent(name, null);
	}
}
