/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Textcontent extends org.jooq.impl.TableImpl<hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord> {

	private static final long serialVersionUID = -2122270068;

	/**
	 * The singleton instance of <code>tilos2.textcontent</code>
	 */
	public static final hu.tilos.radio.jooqmodel.tables.Textcontent TEXTCONTENT = new hu.tilos.radio.jooqmodel.tables.Textcontent();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord> getRecordType() {
		return hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord.class;
	}

	/**
	 * The column <code>tilos2.textcontent.id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>tilos2.textcontent.title</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord, java.lang.String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>tilos2.textcontent.type</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(15).nullable(false), this, "");

	/**
	 * The column <code>tilos2.textcontent.format</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord, java.lang.String> FORMAT = createField("format", org.jooq.impl.SQLDataType.VARCHAR.length(15).nullable(false), this, "");

	/**
	 * The column <code>tilos2.textcontent.content</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord, java.lang.String> CONTENT = createField("content", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>tilos2.textcontent.created</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>tilos2.textcontent.modified</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord, java.sql.Timestamp> MODIFIED = createField("modified", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>tilos2.textcontent.author</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord, java.lang.String> AUTHOR = createField("author", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>tilos2.textcontent.alias</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord, java.lang.String> ALIAS = createField("alias", org.jooq.impl.SQLDataType.VARCHAR.length(60).nullable(false), this, "");

	/**
	 * Create a <code>tilos2.textcontent</code> table reference
	 */
	public Textcontent() {
		this("textcontent", null);
	}

	/**
	 * Create an aliased <code>tilos2.textcontent</code> table reference
	 */
	public Textcontent(java.lang.String alias) {
		this(alias, hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT);
	}

	private Textcontent(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord> aliased) {
		this(alias, aliased, null);
	}

	private Textcontent(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, hu.tilos.radio.jooqmodel.Tilos2.TILOS2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord, java.lang.Integer> getIdentity() {
		return hu.tilos.radio.jooqmodel.Keys.IDENTITY_TEXTCONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord> getPrimaryKey() {
		return hu.tilos.radio.jooqmodel.Keys.KEY_TEXTCONTENT_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord>>asList(hu.tilos.radio.jooqmodel.Keys.KEY_TEXTCONTENT_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public hu.tilos.radio.jooqmodel.tables.Textcontent as(java.lang.String alias) {
		return new hu.tilos.radio.jooqmodel.tables.Textcontent(alias, this);
	}

	/**
	 * Rename this table
	 */
	public hu.tilos.radio.jooqmodel.tables.Textcontent rename(java.lang.String name) {
		return new hu.tilos.radio.jooqmodel.tables.Textcontent(name, null);
	}
}
