/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Url extends org.jooq.impl.TableImpl<hu.tilos.radio.jooqmodel.tables.records.UrlRecord> {

	private static final long serialVersionUID = 191878485;

	/**
	 * The singleton instance of <code>tilos2.url</code>
	 */
	public static final hu.tilos.radio.jooqmodel.tables.Url URL = new hu.tilos.radio.jooqmodel.tables.Url();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<hu.tilos.radio.jooqmodel.tables.records.UrlRecord> getRecordType() {
		return hu.tilos.radio.jooqmodel.tables.records.UrlRecord.class;
	}

	/**
	 * The column <code>tilos2.url.id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.UrlRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>tilos2.url.url</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.UrlRecord, java.lang.String> URL_ = createField("url", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>tilos2.url.type</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.UrlRecord, java.lang.String> TYPE = createField("type", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>tilos2.url</code> table reference
	 */
	public Url() {
		this("url", null);
	}

	/**
	 * Create an aliased <code>tilos2.url</code> table reference
	 */
	public Url(java.lang.String alias) {
		this(alias, hu.tilos.radio.jooqmodel.tables.Url.URL);
	}

	private Url(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.UrlRecord> aliased) {
		this(alias, aliased, null);
	}

	private Url(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.UrlRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, hu.tilos.radio.jooqmodel.Tilos2.TILOS2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.UrlRecord, java.lang.Integer> getIdentity() {
		return hu.tilos.radio.jooqmodel.Keys.IDENTITY_URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.UrlRecord> getPrimaryKey() {
		return hu.tilos.radio.jooqmodel.Keys.KEY_URL_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.UrlRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.UrlRecord>>asList(hu.tilos.radio.jooqmodel.Keys.KEY_URL_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public hu.tilos.radio.jooqmodel.tables.Url as(java.lang.String alias) {
		return new hu.tilos.radio.jooqmodel.tables.Url(alias, this);
	}

	/**
	 * Rename this table
	 */
	public hu.tilos.radio.jooqmodel.tables.Url rename(java.lang.String name) {
		return new hu.tilos.radio.jooqmodel.tables.Url(name, null);
	}
}
