/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User extends org.jooq.impl.TableImpl<hu.tilos.radio.jooqmodel.tables.records.UserRecord> {

	private static final long serialVersionUID = 295792725;

	/**
	 * The singleton instance of <code>tilos2.user</code>
	 */
	public static final hu.tilos.radio.jooqmodel.tables.User USER = new hu.tilos.radio.jooqmodel.tables.User();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<hu.tilos.radio.jooqmodel.tables.records.UserRecord> getRecordType() {
		return hu.tilos.radio.jooqmodel.tables.records.UserRecord.class;
	}

	/**
	 * The column <code>tilos2.user.id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.UserRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>tilos2.user.role_id</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.UserRecord, java.lang.Integer> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>tilos2.user.username</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.UserRecord, java.lang.String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false), this, "");

	/**
	 * The column <code>tilos2.user.password</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.UserRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(40), this, "");

	/**
	 * The column <code>tilos2.user.email</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.UserRecord, java.lang.String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>tilos2.user.salt</code>.
	 */
	public final org.jooq.TableField<hu.tilos.radio.jooqmodel.tables.records.UserRecord, java.lang.String> SALT = createField("salt", org.jooq.impl.SQLDataType.VARCHAR.length(40), this, "");

	/**
	 * Create a <code>tilos2.user</code> table reference
	 */
	public User() {
		this("user", null);
	}

	/**
	 * Create an aliased <code>tilos2.user</code> table reference
	 */
	public User(java.lang.String alias) {
		this(alias, hu.tilos.radio.jooqmodel.tables.User.USER);
	}

	private User(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.UserRecord> aliased) {
		this(alias, aliased, null);
	}

	private User(java.lang.String alias, org.jooq.Table<hu.tilos.radio.jooqmodel.tables.records.UserRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, hu.tilos.radio.jooqmodel.Tilos2.TILOS2, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<hu.tilos.radio.jooqmodel.tables.records.UserRecord, java.lang.Integer> getIdentity() {
		return hu.tilos.radio.jooqmodel.Keys.IDENTITY_USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.UserRecord> getPrimaryKey() {
		return hu.tilos.radio.jooqmodel.Keys.KEY_USER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.UserRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<hu.tilos.radio.jooqmodel.tables.records.UserRecord>>asList(hu.tilos.radio.jooqmodel.Keys.KEY_USER_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.UserRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<hu.tilos.radio.jooqmodel.tables.records.UserRecord, ?>>asList(hu.tilos.radio.jooqmodel.Keys.FK_8D93D649D60322AC);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public hu.tilos.radio.jooqmodel.tables.User as(java.lang.String alias) {
		return new hu.tilos.radio.jooqmodel.tables.User(alias, this);
	}

	/**
	 * Rename this table
	 */
	public hu.tilos.radio.jooqmodel.tables.User rename(java.lang.String name) {
		return new hu.tilos.radio.jooqmodel.tables.User(name, null);
	}
}
