/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApiAuditDao extends org.jooq.impl.DAOImpl<hu.tilos.radio.jooqmodel.tables.records.ApiAuditRecord, hu.tilos.radio.jooqmodel.tables.pojos.ApiAudit, java.lang.Integer> {

	/**
	 * Create a new ApiAuditDao without any configuration
	 */
	public ApiAuditDao() {
		super(hu.tilos.radio.jooqmodel.tables.ApiAudit.API_AUDIT, hu.tilos.radio.jooqmodel.tables.pojos.ApiAudit.class);
	}

	/**
	 * Create a new ApiAuditDao with an attached configuration
	 */
	public ApiAuditDao(org.jooq.Configuration configuration) {
		super(hu.tilos.radio.jooqmodel.tables.ApiAudit.API_AUDIT, hu.tilos.radio.jooqmodel.tables.pojos.ApiAudit.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(hu.tilos.radio.jooqmodel.tables.pojos.ApiAudit object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.ApiAudit> fetchById(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.ApiAudit.API_AUDIT.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public hu.tilos.radio.jooqmodel.tables.pojos.ApiAudit fetchOneById(java.lang.Integer value) {
		return fetchOne(hu.tilos.radio.jooqmodel.tables.ApiAudit.API_AUDIT.ID, value);
	}

	/**
	 * Fetch records that have <code>user IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.ApiAudit> fetchByUser(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.ApiAudit.API_AUDIT.USER, values);
	}

	/**
	 * Fetch records that have <code>url IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.ApiAudit> fetchByUrl(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.ApiAudit.API_AUDIT.URL, values);
	}

	/**
	 * Fetch records that have <code>postParams IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.ApiAudit> fetchByPostparams(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.ApiAudit.API_AUDIT.POSTPARAMS, values);
	}

	/**
	 * Fetch records that have <code>callDate IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.ApiAudit> fetchByCalldate(java.sql.Timestamp... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.ApiAudit.API_AUDIT.CALLDATE, values);
	}

	/**
	 * Fetch records that have <code>method IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.ApiAudit> fetchByMethod(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.ApiAudit.API_AUDIT.METHOD, values);
	}
}
