/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuditDao extends org.jooq.impl.DAOImpl<hu.tilos.radio.jooqmodel.tables.records.AuditRecord, hu.tilos.radio.jooqmodel.tables.pojos.Audit, java.lang.Integer> {

	/**
	 * Create a new AuditDao without any configuration
	 */
	public AuditDao() {
		super(hu.tilos.radio.jooqmodel.tables.Audit.AUDIT, hu.tilos.radio.jooqmodel.tables.pojos.Audit.class);
	}

	/**
	 * Create a new AuditDao with an attached configuration
	 */
	public AuditDao(org.jooq.Configuration configuration) {
		super(hu.tilos.radio.jooqmodel.tables.Audit.AUDIT, hu.tilos.radio.jooqmodel.tables.pojos.Audit.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(hu.tilos.radio.jooqmodel.tables.pojos.Audit object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Audit> fetchById(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Audit.AUDIT.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public hu.tilos.radio.jooqmodel.tables.pojos.Audit fetchOneById(java.lang.Integer value) {
		return fetchOne(hu.tilos.radio.jooqmodel.tables.Audit.AUDIT.ID, value);
	}

	/**
	 * Fetch records that have <code>user IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Audit> fetchByUser(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Audit.AUDIT.USER, values);
	}

	/**
	 * Fetch records that have <code>url IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Audit> fetchByUrl(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Audit.AUDIT.URL, values);
	}

	/**
	 * Fetch records that have <code>postParams IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Audit> fetchByPostparams(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Audit.AUDIT.POSTPARAMS, values);
	}
}
