/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorDao extends org.jooq.impl.DAOImpl<hu.tilos.radio.jooqmodel.tables.records.AuthorRecord, hu.tilos.radio.jooqmodel.tables.pojos.Author, java.lang.Integer> {

	/**
	 * Create a new AuthorDao without any configuration
	 */
	public AuthorDao() {
		super(hu.tilos.radio.jooqmodel.tables.Author.AUTHOR, hu.tilos.radio.jooqmodel.tables.pojos.Author.class);
	}

	/**
	 * Create a new AuthorDao with an attached configuration
	 */
	public AuthorDao(org.jooq.Configuration configuration) {
		super(hu.tilos.radio.jooqmodel.tables.Author.AUTHOR, hu.tilos.radio.jooqmodel.tables.pojos.Author.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(hu.tilos.radio.jooqmodel.tables.pojos.Author object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Author> fetchById(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Author.AUTHOR.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public hu.tilos.radio.jooqmodel.tables.pojos.Author fetchOneById(java.lang.Integer value) {
		return fetchOne(hu.tilos.radio.jooqmodel.tables.Author.AUTHOR.ID, value);
	}

	/**
	 * Fetch records that have <code>user_id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Author> fetchByUserId(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Author.AUTHOR.USER_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>user_id = value</code>
	 */
	public hu.tilos.radio.jooqmodel.tables.pojos.Author fetchOneByUserId(java.lang.Integer value) {
		return fetchOne(hu.tilos.radio.jooqmodel.tables.Author.AUTHOR.USER_ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Author> fetchByName(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Author.AUTHOR.NAME, values);
	}

	/**
	 * Fetch records that have <code>alias IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Author> fetchByAlias(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Author.AUTHOR.ALIAS, values);
	}

	/**
	 * Fetch records that have <code>photo IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Author> fetchByPhoto(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Author.AUTHOR.PHOTO, values);
	}

	/**
	 * Fetch records that have <code>avatar IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Author> fetchByAvatar(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Author.AUTHOR.AVATAR, values);
	}

	/**
	 * Fetch records that have <code>introduction IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Author> fetchByIntroduction(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Author.AUTHOR.INTRODUCTION, values);
	}

	/**
	 * Fetch records that have <code>email IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Author> fetchByEmail(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Author.AUTHOR.EMAIL, values);
	}
}
