/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorUrlDao extends org.jooq.impl.DAOImpl<hu.tilos.radio.jooqmodel.tables.records.AuthorUrlRecord, hu.tilos.radio.jooqmodel.tables.pojos.AuthorUrl, org.jooq.Record2<java.lang.Integer, java.lang.Integer>> {

	/**
	 * Create a new AuthorUrlDao without any configuration
	 */
	public AuthorUrlDao() {
		super(hu.tilos.radio.jooqmodel.tables.AuthorUrl.AUTHOR_URL, hu.tilos.radio.jooqmodel.tables.pojos.AuthorUrl.class);
	}

	/**
	 * Create a new AuthorUrlDao with an attached configuration
	 */
	public AuthorUrlDao(org.jooq.Configuration configuration) {
		super(hu.tilos.radio.jooqmodel.tables.AuthorUrl.AUTHOR_URL, hu.tilos.radio.jooqmodel.tables.pojos.AuthorUrl.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected org.jooq.Record2<java.lang.Integer, java.lang.Integer> getId(hu.tilos.radio.jooqmodel.tables.pojos.AuthorUrl object) {
		return compositeKeyRecord(object.getAuthorId(), object.getUrlId());
	}

	/**
	 * Fetch records that have <code>author_id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.AuthorUrl> fetchByAuthorId(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.AuthorUrl.AUTHOR_URL.AUTHOR_ID, values);
	}

	/**
	 * Fetch records that have <code>url_id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.AuthorUrl> fetchByUrlId(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.AuthorUrl.AUTHOR_URL.URL_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>url_id = value</code>
	 */
	public hu.tilos.radio.jooqmodel.tables.pojos.AuthorUrl fetchOneByUrlId(java.lang.Integer value) {
		return fetchOne(hu.tilos.radio.jooqmodel.tables.AuthorUrl.AUTHOR_URL.URL_ID, value);
	}
}
