/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookmarkDao extends org.jooq.impl.DAOImpl<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord, hu.tilos.radio.jooqmodel.tables.pojos.Bookmark, java.lang.Integer> {

	/**
	 * Create a new BookmarkDao without any configuration
	 */
	public BookmarkDao() {
		super(hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK, hu.tilos.radio.jooqmodel.tables.pojos.Bookmark.class);
	}

	/**
	 * Create a new BookmarkDao with an attached configuration
	 */
	public BookmarkDao(org.jooq.Configuration configuration) {
		super(hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK, hu.tilos.radio.jooqmodel.tables.pojos.Bookmark.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(hu.tilos.radio.jooqmodel.tables.pojos.Bookmark object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Bookmark> fetchById(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public hu.tilos.radio.jooqmodel.tables.pojos.Bookmark fetchOneById(java.lang.Integer value) {
		return fetchOne(hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK.ID, value);
	}

	/**
	 * Fetch records that have <code>radioshow_id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Bookmark> fetchByRadioshowId(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK.RADIOSHOW_ID, values);
	}

	/**
	 * Fetch records that have <code>episode_id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Bookmark> fetchByEpisodeId(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK.EPISODE_ID, values);
	}

	/**
	 * Fetch records that have <code>user_id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Bookmark> fetchByUserId(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK.USER_ID, values);
	}

	/**
	 * Fetch records that have <code>from IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Bookmark> fetchByFrom(java.sql.Timestamp... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK.FROM, values);
	}

	/**
	 * Fetch records that have <code>to IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Bookmark> fetchByTo(java.sql.Timestamp... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK.TO, values);
	}

	/**
	 * Fetch records that have <code>modified IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Bookmark> fetchByModified(java.sql.Timestamp... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK.MODIFIED, values);
	}

	/**
	 * Fetch records that have <code>title IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Bookmark> fetchByTitle(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK.TITLE, values);
	}

	/**
	 * Fetch records that have <code>content IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Bookmark> fetchByContent(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK.CONTENT, values);
	}
}
