/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChangePasswordDao extends org.jooq.impl.DAOImpl<hu.tilos.radio.jooqmodel.tables.records.ChangePasswordRecord, hu.tilos.radio.jooqmodel.tables.pojos.ChangePassword, java.lang.Integer> {

	/**
	 * Create a new ChangePasswordDao without any configuration
	 */
	public ChangePasswordDao() {
		super(hu.tilos.radio.jooqmodel.tables.ChangePassword.CHANGE_PASSWORD, hu.tilos.radio.jooqmodel.tables.pojos.ChangePassword.class);
	}

	/**
	 * Create a new ChangePasswordDao with an attached configuration
	 */
	public ChangePasswordDao(org.jooq.Configuration configuration) {
		super(hu.tilos.radio.jooqmodel.tables.ChangePassword.CHANGE_PASSWORD, hu.tilos.radio.jooqmodel.tables.pojos.ChangePassword.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(hu.tilos.radio.jooqmodel.tables.pojos.ChangePassword object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.ChangePassword> fetchById(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.ChangePassword.CHANGE_PASSWORD.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public hu.tilos.radio.jooqmodel.tables.pojos.ChangePassword fetchOneById(java.lang.Integer value) {
		return fetchOne(hu.tilos.radio.jooqmodel.tables.ChangePassword.CHANGE_PASSWORD.ID, value);
	}

	/**
	 * Fetch records that have <code>user_id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.ChangePassword> fetchByUserId(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.ChangePassword.CHANGE_PASSWORD.USER_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>user_id = value</code>
	 */
	public hu.tilos.radio.jooqmodel.tables.pojos.ChangePassword fetchOneByUserId(java.lang.Integer value) {
		return fetchOne(hu.tilos.radio.jooqmodel.tables.ChangePassword.CHANGE_PASSWORD.USER_ID, value);
	}

	/**
	 * Fetch records that have <code>token IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.ChangePassword> fetchByToken(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.ChangePassword.CHANGE_PASSWORD.TOKEN, values);
	}

	/**
	 * Fetch records that have <code>created IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.ChangePassword> fetchByCreated(java.sql.Timestamp... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.ChangePassword.CHANGE_PASSWORD.CREATED, values);
	}
}
