/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ContributionDao extends org.jooq.impl.DAOImpl<hu.tilos.radio.jooqmodel.tables.records.ContributionRecord, hu.tilos.radio.jooqmodel.tables.pojos.Contribution, java.lang.Integer> {

	/**
	 * Create a new ContributionDao without any configuration
	 */
	public ContributionDao() {
		super(hu.tilos.radio.jooqmodel.tables.Contribution.CONTRIBUTION, hu.tilos.radio.jooqmodel.tables.pojos.Contribution.class);
	}

	/**
	 * Create a new ContributionDao with an attached configuration
	 */
	public ContributionDao(org.jooq.Configuration configuration) {
		super(hu.tilos.radio.jooqmodel.tables.Contribution.CONTRIBUTION, hu.tilos.radio.jooqmodel.tables.pojos.Contribution.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(hu.tilos.radio.jooqmodel.tables.pojos.Contribution object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Contribution> fetchById(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Contribution.CONTRIBUTION.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public hu.tilos.radio.jooqmodel.tables.pojos.Contribution fetchOneById(java.lang.Integer value) {
		return fetchOne(hu.tilos.radio.jooqmodel.tables.Contribution.CONTRIBUTION.ID, value);
	}

	/**
	 * Fetch records that have <code>radioshow_id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Contribution> fetchByRadioshowId(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Contribution.CONTRIBUTION.RADIOSHOW_ID, values);
	}

	/**
	 * Fetch records that have <code>author_id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Contribution> fetchByAuthorId(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Contribution.CONTRIBUTION.AUTHOR_ID, values);
	}

	/**
	 * Fetch records that have <code>nick IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Contribution> fetchByNick(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Contribution.CONTRIBUTION.NICK, values);
	}
}
