/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EpisodeDao extends org.jooq.impl.DAOImpl<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord, hu.tilos.radio.jooqmodel.tables.pojos.Episode, java.lang.Integer> {

	/**
	 * Create a new EpisodeDao without any configuration
	 */
	public EpisodeDao() {
		super(hu.tilos.radio.jooqmodel.tables.Episode.EPISODE, hu.tilos.radio.jooqmodel.tables.pojos.Episode.class);
	}

	/**
	 * Create a new EpisodeDao with an attached configuration
	 */
	public EpisodeDao(org.jooq.Configuration configuration) {
		super(hu.tilos.radio.jooqmodel.tables.Episode.EPISODE, hu.tilos.radio.jooqmodel.tables.pojos.Episode.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(hu.tilos.radio.jooqmodel.tables.pojos.Episode object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Episode> fetchById(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Episode.EPISODE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public hu.tilos.radio.jooqmodel.tables.pojos.Episode fetchOneById(java.lang.Integer value) {
		return fetchOne(hu.tilos.radio.jooqmodel.tables.Episode.EPISODE.ID, value);
	}

	/**
	 * Fetch records that have <code>radioshow_id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Episode> fetchByRadioshowId(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Episode.EPISODE.RADIOSHOW_ID, values);
	}

	/**
	 * Fetch records that have <code>textcontent_id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Episode> fetchByTextcontentId(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Episode.EPISODE.TEXTCONTENT_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>textcontent_id = value</code>
	 */
	public hu.tilos.radio.jooqmodel.tables.pojos.Episode fetchOneByTextcontentId(java.lang.Integer value) {
		return fetchOne(hu.tilos.radio.jooqmodel.tables.Episode.EPISODE.TEXTCONTENT_ID, value);
	}

	/**
	 * Fetch records that have <code>plannedFrom IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Episode> fetchByPlannedfrom(java.sql.Timestamp... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Episode.EPISODE.PLANNEDFROM, values);
	}

	/**
	 * Fetch records that have <code>plannedTo IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Episode> fetchByPlannedto(java.sql.Timestamp... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Episode.EPISODE.PLANNEDTO, values);
	}

	/**
	 * Fetch records that have <code>realFrom IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Episode> fetchByRealfrom(java.sql.Timestamp... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Episode.EPISODE.REALFROM, values);
	}

	/**
	 * Fetch records that have <code>realTo IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Episode> fetchByRealto(java.sql.Timestamp... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Episode.EPISODE.REALTO, values);
	}
}
