/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ListenerStatDao extends org.jooq.impl.DAOImpl<hu.tilos.radio.jooqmodel.tables.records.ListenerStatRecord, hu.tilos.radio.jooqmodel.tables.pojos.ListenerStat, java.lang.Integer> {

	/**
	 * Create a new ListenerStatDao without any configuration
	 */
	public ListenerStatDao() {
		super(hu.tilos.radio.jooqmodel.tables.ListenerStat.LISTENER_STAT, hu.tilos.radio.jooqmodel.tables.pojos.ListenerStat.class);
	}

	/**
	 * Create a new ListenerStatDao with an attached configuration
	 */
	public ListenerStatDao(org.jooq.Configuration configuration) {
		super(hu.tilos.radio.jooqmodel.tables.ListenerStat.LISTENER_STAT, hu.tilos.radio.jooqmodel.tables.pojos.ListenerStat.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(hu.tilos.radio.jooqmodel.tables.pojos.ListenerStat object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.ListenerStat> fetchById(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.ListenerStat.LISTENER_STAT.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public hu.tilos.radio.jooqmodel.tables.pojos.ListenerStat fetchOneById(java.lang.Integer value) {
		return fetchOne(hu.tilos.radio.jooqmodel.tables.ListenerStat.LISTENER_STAT.ID, value);
	}

	/**
	 * Fetch records that have <code>type IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.ListenerStat> fetchByType(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.ListenerStat.LISTENER_STAT.TYPE, values);
	}

	/**
	 * Fetch records that have <code>count IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.ListenerStat> fetchByCount(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.ListenerStat.LISTENER_STAT.COUNT, values);
	}

	/**
	 * Fetch records that have <code>date IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.ListenerStat> fetchByDate(java.sql.Timestamp... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.ListenerStat.LISTENER_STAT.DATE, values);
	}
}
