/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MigrationVersionsDao extends org.jooq.impl.DAOImpl<hu.tilos.radio.jooqmodel.tables.records.MigrationVersionsRecord, hu.tilos.radio.jooqmodel.tables.pojos.MigrationVersions, java.lang.String> {

	/**
	 * Create a new MigrationVersionsDao without any configuration
	 */
	public MigrationVersionsDao() {
		super(hu.tilos.radio.jooqmodel.tables.MigrationVersions.MIGRATION_VERSIONS, hu.tilos.radio.jooqmodel.tables.pojos.MigrationVersions.class);
	}

	/**
	 * Create a new MigrationVersionsDao with an attached configuration
	 */
	public MigrationVersionsDao(org.jooq.Configuration configuration) {
		super(hu.tilos.radio.jooqmodel.tables.MigrationVersions.MIGRATION_VERSIONS, hu.tilos.radio.jooqmodel.tables.pojos.MigrationVersions.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.String getId(hu.tilos.radio.jooqmodel.tables.pojos.MigrationVersions object) {
		return object.getVersion();
	}

	/**
	 * Fetch records that have <code>version IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.MigrationVersions> fetchByVersion(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.MigrationVersions.MIGRATION_VERSIONS.VERSION, values);
	}

	/**
	 * Fetch a unique record that has <code>version = value</code>
	 */
	public hu.tilos.radio.jooqmodel.tables.pojos.MigrationVersions fetchOneByVersion(java.lang.String value) {
		return fetchOne(hu.tilos.radio.jooqmodel.tables.MigrationVersions.MIGRATION_VERSIONS.VERSION, value);
	}
}
