/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MixDao extends org.jooq.impl.DAOImpl<hu.tilos.radio.jooqmodel.tables.records.MixRecord, hu.tilos.radio.jooqmodel.tables.pojos.Mix, java.lang.Integer> {

	/**
	 * Create a new MixDao without any configuration
	 */
	public MixDao() {
		super(hu.tilos.radio.jooqmodel.tables.Mix.MIX, hu.tilos.radio.jooqmodel.tables.pojos.Mix.class);
	}

	/**
	 * Create a new MixDao with an attached configuration
	 */
	public MixDao(org.jooq.Configuration configuration) {
		super(hu.tilos.radio.jooqmodel.tables.Mix.MIX, hu.tilos.radio.jooqmodel.tables.pojos.Mix.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(hu.tilos.radio.jooqmodel.tables.pojos.Mix object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Mix> fetchById(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Mix.MIX.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public hu.tilos.radio.jooqmodel.tables.pojos.Mix fetchOneById(java.lang.Integer value) {
		return fetchOne(hu.tilos.radio.jooqmodel.tables.Mix.MIX.ID, value);
	}

	/**
	 * Fetch records that have <code>show_id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Mix> fetchByShowId(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Mix.MIX.SHOW_ID, values);
	}

	/**
	 * Fetch records that have <code>author IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Mix> fetchByAuthor(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Mix.MIX.AUTHOR, values);
	}

	/**
	 * Fetch records that have <code>title IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Mix> fetchByTitle(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Mix.MIX.TITLE, values);
	}

	/**
	 * Fetch records that have <code>file IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Mix> fetchByFile(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Mix.MIX.FILE, values);
	}

	/**
	 * Fetch records that have <code>date IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Mix> fetchByDate(java.sql.Date... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Mix.MIX.DATE, values);
	}

	/**
	 * Fetch records that have <code>type IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Mix> fetchByType(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Mix.MIX.TYPE, values);
	}
}
