/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RoleDao extends org.jooq.impl.DAOImpl<hu.tilos.radio.jooqmodel.tables.records.RoleRecord, hu.tilos.radio.jooqmodel.tables.pojos.Role, java.lang.Integer> {

	/**
	 * Create a new RoleDao without any configuration
	 */
	public RoleDao() {
		super(hu.tilos.radio.jooqmodel.tables.Role.ROLE, hu.tilos.radio.jooqmodel.tables.pojos.Role.class);
	}

	/**
	 * Create a new RoleDao with an attached configuration
	 */
	public RoleDao(org.jooq.Configuration configuration) {
		super(hu.tilos.radio.jooqmodel.tables.Role.ROLE, hu.tilos.radio.jooqmodel.tables.pojos.Role.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(hu.tilos.radio.jooqmodel.tables.pojos.Role object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Role> fetchById(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Role.ROLE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public hu.tilos.radio.jooqmodel.tables.pojos.Role fetchOneById(java.lang.Integer value) {
		return fetchOne(hu.tilos.radio.jooqmodel.tables.Role.ROLE.ID, value);
	}

	/**
	 * Fetch records that have <code>parent_role_id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Role> fetchByParentRoleId(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Role.ROLE.PARENT_ROLE_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>parent_role_id = value</code>
	 */
	public hu.tilos.radio.jooqmodel.tables.pojos.Role fetchOneByParentRoleId(java.lang.Integer value) {
		return fetchOne(hu.tilos.radio.jooqmodel.tables.Role.ROLE.PARENT_ROLE_ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Role> fetchByName(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Role.ROLE.NAME, values);
	}
}
