/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SchedulingDao extends org.jooq.impl.DAOImpl<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord, hu.tilos.radio.jooqmodel.tables.pojos.Scheduling, java.lang.Integer> {

	/**
	 * Create a new SchedulingDao without any configuration
	 */
	public SchedulingDao() {
		super(hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING, hu.tilos.radio.jooqmodel.tables.pojos.Scheduling.class);
	}

	/**
	 * Create a new SchedulingDao with an attached configuration
	 */
	public SchedulingDao(org.jooq.Configuration configuration) {
		super(hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING, hu.tilos.radio.jooqmodel.tables.pojos.Scheduling.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(hu.tilos.radio.jooqmodel.tables.pojos.Scheduling object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Scheduling> fetchById(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public hu.tilos.radio.jooqmodel.tables.pojos.Scheduling fetchOneById(java.lang.Integer value) {
		return fetchOne(hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING.ID, value);
	}

	/**
	 * Fetch records that have <code>radioshow_id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Scheduling> fetchByRadioshowId(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING.RADIOSHOW_ID, values);
	}

	/**
	 * Fetch records that have <code>weekType IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Scheduling> fetchByWeektype(java.lang.Short... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING.WEEKTYPE, values);
	}

	/**
	 * Fetch records that have <code>base IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Scheduling> fetchByBase(java.sql.Date... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING.BASE, values);
	}

	/**
	 * Fetch records that have <code>weekDay IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Scheduling> fetchByWeekday(java.lang.Short... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING.WEEKDAY, values);
	}

	/**
	 * Fetch records that have <code>hourFrom IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Scheduling> fetchByHourfrom(java.lang.Short... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING.HOURFROM, values);
	}

	/**
	 * Fetch records that have <code>minFrom IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Scheduling> fetchByMinfrom(java.lang.Short... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING.MINFROM, values);
	}

	/**
	 * Fetch records that have <code>duration IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Scheduling> fetchByDuration(java.lang.Short... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING.DURATION, values);
	}

	/**
	 * Fetch records that have <code>validFrom IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Scheduling> fetchByValidfrom(java.sql.Date... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING.VALIDFROM, values);
	}

	/**
	 * Fetch records that have <code>validTo IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Scheduling> fetchByValidto(java.sql.Date... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING.VALIDTO, values);
	}
}
