/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagDao extends org.jooq.impl.DAOImpl<hu.tilos.radio.jooqmodel.tables.records.TagRecord, hu.tilos.radio.jooqmodel.tables.pojos.Tag, java.lang.Integer> {

	/**
	 * Create a new TagDao without any configuration
	 */
	public TagDao() {
		super(hu.tilos.radio.jooqmodel.tables.Tag.TAG, hu.tilos.radio.jooqmodel.tables.pojos.Tag.class);
	}

	/**
	 * Create a new TagDao with an attached configuration
	 */
	public TagDao(org.jooq.Configuration configuration) {
		super(hu.tilos.radio.jooqmodel.tables.Tag.TAG, hu.tilos.radio.jooqmodel.tables.pojos.Tag.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(hu.tilos.radio.jooqmodel.tables.pojos.Tag object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Tag> fetchById(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Tag.TAG.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public hu.tilos.radio.jooqmodel.tables.pojos.Tag fetchOneById(java.lang.Integer value) {
		return fetchOne(hu.tilos.radio.jooqmodel.tables.Tag.TAG.ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Tag> fetchByName(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Tag.TAG.NAME, values);
	}

	/**
	 * Fetch records that have <code>type IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Tag> fetchByType(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Tag.TAG.TYPE, values);
	}
}
