/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagTextcontentDao extends org.jooq.impl.DAOImpl<hu.tilos.radio.jooqmodel.tables.records.TagTextcontentRecord, hu.tilos.radio.jooqmodel.tables.pojos.TagTextcontent, org.jooq.Record2<java.lang.Integer, java.lang.Integer>> {

	/**
	 * Create a new TagTextcontentDao without any configuration
	 */
	public TagTextcontentDao() {
		super(hu.tilos.radio.jooqmodel.tables.TagTextcontent.TAG_TEXTCONTENT, hu.tilos.radio.jooqmodel.tables.pojos.TagTextcontent.class);
	}

	/**
	 * Create a new TagTextcontentDao with an attached configuration
	 */
	public TagTextcontentDao(org.jooq.Configuration configuration) {
		super(hu.tilos.radio.jooqmodel.tables.TagTextcontent.TAG_TEXTCONTENT, hu.tilos.radio.jooqmodel.tables.pojos.TagTextcontent.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected org.jooq.Record2<java.lang.Integer, java.lang.Integer> getId(hu.tilos.radio.jooqmodel.tables.pojos.TagTextcontent object) {
		return compositeKeyRecord(object.getTextcontentId(), object.getTagId());
	}

	/**
	 * Fetch records that have <code>textcontent_id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.TagTextcontent> fetchByTextcontentId(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.TagTextcontent.TAG_TEXTCONTENT.TEXTCONTENT_ID, values);
	}

	/**
	 * Fetch records that have <code>tag_id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.TagTextcontent> fetchByTagId(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.TagTextcontent.TAG_TEXTCONTENT.TAG_ID, values);
	}
}
