/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TextcontentDao extends org.jooq.impl.DAOImpl<hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord, hu.tilos.radio.jooqmodel.tables.pojos.Textcontent, java.lang.Integer> {

	/**
	 * Create a new TextcontentDao without any configuration
	 */
	public TextcontentDao() {
		super(hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT, hu.tilos.radio.jooqmodel.tables.pojos.Textcontent.class);
	}

	/**
	 * Create a new TextcontentDao with an attached configuration
	 */
	public TextcontentDao(org.jooq.Configuration configuration) {
		super(hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT, hu.tilos.radio.jooqmodel.tables.pojos.Textcontent.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(hu.tilos.radio.jooqmodel.tables.pojos.Textcontent object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Textcontent> fetchById(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public hu.tilos.radio.jooqmodel.tables.pojos.Textcontent fetchOneById(java.lang.Integer value) {
		return fetchOne(hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT.ID, value);
	}

	/**
	 * Fetch records that have <code>title IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Textcontent> fetchByTitle(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT.TITLE, values);
	}

	/**
	 * Fetch records that have <code>type IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Textcontent> fetchByType(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT.TYPE, values);
	}

	/**
	 * Fetch records that have <code>format IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Textcontent> fetchByFormat(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT.FORMAT, values);
	}

	/**
	 * Fetch records that have <code>content IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Textcontent> fetchByContent(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT.CONTENT, values);
	}

	/**
	 * Fetch records that have <code>created IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Textcontent> fetchByCreated(java.sql.Timestamp... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT.CREATED, values);
	}

	/**
	 * Fetch records that have <code>modified IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Textcontent> fetchByModified(java.sql.Timestamp... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT.MODIFIED, values);
	}

	/**
	 * Fetch records that have <code>author IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Textcontent> fetchByAuthor(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT.AUTHOR, values);
	}

	/**
	 * Fetch records that have <code>alias IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Textcontent> fetchByAlias(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT.ALIAS, values);
	}
}
