/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UrlDao extends org.jooq.impl.DAOImpl<hu.tilos.radio.jooqmodel.tables.records.UrlRecord, hu.tilos.radio.jooqmodel.tables.pojos.Url, java.lang.Integer> {

	/**
	 * Create a new UrlDao without any configuration
	 */
	public UrlDao() {
		super(hu.tilos.radio.jooqmodel.tables.Url.URL, hu.tilos.radio.jooqmodel.tables.pojos.Url.class);
	}

	/**
	 * Create a new UrlDao with an attached configuration
	 */
	public UrlDao(org.jooq.Configuration configuration) {
		super(hu.tilos.radio.jooqmodel.tables.Url.URL, hu.tilos.radio.jooqmodel.tables.pojos.Url.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(hu.tilos.radio.jooqmodel.tables.pojos.Url object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Url> fetchById(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Url.URL.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public hu.tilos.radio.jooqmodel.tables.pojos.Url fetchOneById(java.lang.Integer value) {
		return fetchOne(hu.tilos.radio.jooqmodel.tables.Url.URL.ID, value);
	}

	/**
	 * Fetch records that have <code>url IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Url> fetchByUrl(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Url.URL.URL_, values);
	}

	/**
	 * Fetch records that have <code>type IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.Url> fetchByType(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.Url.URL.TYPE, values);
	}
}
