/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDao extends org.jooq.impl.DAOImpl<hu.tilos.radio.jooqmodel.tables.records.UserRecord, hu.tilos.radio.jooqmodel.tables.pojos.User, java.lang.Integer> {

	/**
	 * Create a new UserDao without any configuration
	 */
	public UserDao() {
		super(hu.tilos.radio.jooqmodel.tables.User.USER, hu.tilos.radio.jooqmodel.tables.pojos.User.class);
	}

	/**
	 * Create a new UserDao with an attached configuration
	 */
	public UserDao(org.jooq.Configuration configuration) {
		super(hu.tilos.radio.jooqmodel.tables.User.USER, hu.tilos.radio.jooqmodel.tables.pojos.User.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(hu.tilos.radio.jooqmodel.tables.pojos.User object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.User> fetchById(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.User.USER.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public hu.tilos.radio.jooqmodel.tables.pojos.User fetchOneById(java.lang.Integer value) {
		return fetchOne(hu.tilos.radio.jooqmodel.tables.User.USER.ID, value);
	}

	/**
	 * Fetch records that have <code>role_id IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.User> fetchByRoleId(java.lang.Integer... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.User.USER.ROLE_ID, values);
	}

	/**
	 * Fetch records that have <code>username IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.User> fetchByUsername(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.User.USER.USERNAME, values);
	}

	/**
	 * Fetch records that have <code>password IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.User> fetchByPassword(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.User.USER.PASSWORD, values);
	}

	/**
	 * Fetch records that have <code>email IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.User> fetchByEmail(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.User.USER.EMAIL, values);
	}

	/**
	 * Fetch records that have <code>salt IN (values)</code>
	 */
	public java.util.List<hu.tilos.radio.jooqmodel.tables.pojos.User> fetchBySalt(java.lang.String... values) {
		return fetch(hu.tilos.radio.jooqmodel.tables.User.USER.SALT, values);
	}
}
