/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ApiAuditRecord extends org.jooq.impl.UpdatableRecordImpl<hu.tilos.radio.jooqmodel.tables.records.ApiAuditRecord> implements org.jooq.Record6<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String> {

	private static final long serialVersionUID = -1558008193;

	/**
	 * Setter for <code>tilos2.api_audit.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>tilos2.api_audit.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>tilos2.api_audit.user</code>.
	 */
	public void setUser(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>tilos2.api_audit.user</code>.
	 */
	public java.lang.String getUser() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>tilos2.api_audit.url</code>.
	 */
	public void setUrl(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>tilos2.api_audit.url</code>.
	 */
	public java.lang.String getUrl() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>tilos2.api_audit.postParams</code>.
	 */
	public void setPostparams(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>tilos2.api_audit.postParams</code>.
	 */
	public java.lang.String getPostparams() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>tilos2.api_audit.callDate</code>.
	 */
	public void setCalldate(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>tilos2.api_audit.callDate</code>.
	 */
	public java.sql.Timestamp getCalldate() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>tilos2.api_audit.method</code>.
	 */
	public void setMethod(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>tilos2.api_audit.method</code>.
	 */
	public java.lang.String getMethod() {
		return (java.lang.String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return hu.tilos.radio.jooqmodel.tables.ApiAudit.API_AUDIT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return hu.tilos.radio.jooqmodel.tables.ApiAudit.API_AUDIT.USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return hu.tilos.radio.jooqmodel.tables.ApiAudit.API_AUDIT.URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return hu.tilos.radio.jooqmodel.tables.ApiAudit.API_AUDIT.POSTPARAMS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return hu.tilos.radio.jooqmodel.tables.ApiAudit.API_AUDIT.CALLDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return hu.tilos.radio.jooqmodel.tables.ApiAudit.API_AUDIT.METHOD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getPostparams();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getCalldate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getMethod();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ApiAuditRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ApiAuditRecord value2(java.lang.String value) {
		setUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ApiAuditRecord value3(java.lang.String value) {
		setUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ApiAuditRecord value4(java.lang.String value) {
		setPostparams(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ApiAuditRecord value5(java.sql.Timestamp value) {
		setCalldate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ApiAuditRecord value6(java.lang.String value) {
		setMethod(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ApiAuditRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.sql.Timestamp value5, java.lang.String value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ApiAuditRecord
	 */
	public ApiAuditRecord() {
		super(hu.tilos.radio.jooqmodel.tables.ApiAudit.API_AUDIT);
	}

	/**
	 * Create a detached, initialised ApiAuditRecord
	 */
	public ApiAuditRecord(java.lang.Integer id, java.lang.String user, java.lang.String url, java.lang.String postparams, java.sql.Timestamp calldate, java.lang.String method) {
		super(hu.tilos.radio.jooqmodel.tables.ApiAudit.API_AUDIT);

		setValue(0, id);
		setValue(1, user);
		setValue(2, url);
		setValue(3, postparams);
		setValue(4, calldate);
		setValue(5, method);
	}
}
