/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuditRecord extends org.jooq.impl.UpdatableRecordImpl<hu.tilos.radio.jooqmodel.tables.records.AuditRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1634034660;

	/**
	 * Setter for <code>tilos2.audit.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>tilos2.audit.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>tilos2.audit.user</code>.
	 */
	public void setUser(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>tilos2.audit.user</code>.
	 */
	public java.lang.String getUser() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>tilos2.audit.url</code>.
	 */
	public void setUrl(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>tilos2.audit.url</code>.
	 */
	public java.lang.String getUrl() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>tilos2.audit.postParams</code>.
	 */
	public void setPostparams(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>tilos2.audit.postParams</code>.
	 */
	public java.lang.String getPostparams() {
		return (java.lang.String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return hu.tilos.radio.jooqmodel.tables.Audit.AUDIT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return hu.tilos.radio.jooqmodel.tables.Audit.AUDIT.USER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return hu.tilos.radio.jooqmodel.tables.Audit.AUDIT.URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return hu.tilos.radio.jooqmodel.tables.Audit.AUDIT.POSTPARAMS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUser();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getPostparams();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AuditRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AuditRecord value2(java.lang.String value) {
		setUser(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AuditRecord value3(java.lang.String value) {
		setUrl(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AuditRecord value4(java.lang.String value) {
		setPostparams(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AuditRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AuditRecord
	 */
	public AuditRecord() {
		super(hu.tilos.radio.jooqmodel.tables.Audit.AUDIT);
	}

	/**
	 * Create a detached, initialised AuditRecord
	 */
	public AuditRecord(java.lang.Integer id, java.lang.String user, java.lang.String url, java.lang.String postparams) {
		super(hu.tilos.radio.jooqmodel.tables.Audit.AUDIT);

		setValue(0, id);
		setValue(1, user);
		setValue(2, url);
		setValue(3, postparams);
	}
}
