/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookmarkRecord extends org.jooq.impl.UpdatableRecordImpl<hu.tilos.radio.jooqmodel.tables.records.BookmarkRecord> implements org.jooq.Record9<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 498530649;

	/**
	 * Setter for <code>tilos2.bookmark.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>tilos2.bookmark.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>tilos2.bookmark.radioshow_id</code>.
	 */
	public void setRadioshowId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>tilos2.bookmark.radioshow_id</code>.
	 */
	public java.lang.Integer getRadioshowId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>tilos2.bookmark.episode_id</code>.
	 */
	public void setEpisodeId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>tilos2.bookmark.episode_id</code>.
	 */
	public java.lang.Integer getEpisodeId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>tilos2.bookmark.user_id</code>.
	 */
	public void setUserId(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>tilos2.bookmark.user_id</code>.
	 */
	public java.lang.Integer getUserId() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>tilos2.bookmark.from</code>.
	 */
	public void setFrom(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>tilos2.bookmark.from</code>.
	 */
	public java.sql.Timestamp getFrom() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>tilos2.bookmark.to</code>.
	 */
	public void setTo(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>tilos2.bookmark.to</code>.
	 */
	public java.sql.Timestamp getTo() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>tilos2.bookmark.modified</code>.
	 */
	public void setModified(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>tilos2.bookmark.modified</code>.
	 */
	public java.sql.Timestamp getModified() {
		return (java.sql.Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>tilos2.bookmark.title</code>.
	 */
	public void setTitle(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>tilos2.bookmark.title</code>.
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>tilos2.bookmark.content</code>.
	 */
	public void setContent(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>tilos2.bookmark.content</code>.
	 */
	public java.lang.String getContent() {
		return (java.lang.String) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK.RADIOSHOW_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK.EPISODE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK.FROM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK.TO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK.MODIFIED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getRadioshowId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getEpisodeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getFrom();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getTo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getModified();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookmarkRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookmarkRecord value2(java.lang.Integer value) {
		setRadioshowId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookmarkRecord value3(java.lang.Integer value) {
		setEpisodeId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookmarkRecord value4(java.lang.Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookmarkRecord value5(java.sql.Timestamp value) {
		setFrom(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookmarkRecord value6(java.sql.Timestamp value) {
		setTo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookmarkRecord value7(java.sql.Timestamp value) {
		setModified(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookmarkRecord value8(java.lang.String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookmarkRecord value9(java.lang.String value) {
		setContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookmarkRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.Integer value4, java.sql.Timestamp value5, java.sql.Timestamp value6, java.sql.Timestamp value7, java.lang.String value8, java.lang.String value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached BookmarkRecord
	 */
	public BookmarkRecord() {
		super(hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK);
	}

	/**
	 * Create a detached, initialised BookmarkRecord
	 */
	public BookmarkRecord(java.lang.Integer id, java.lang.Integer radioshowId, java.lang.Integer episodeId, java.lang.Integer userId, java.sql.Timestamp from, java.sql.Timestamp to, java.sql.Timestamp modified, java.lang.String title, java.lang.String content) {
		super(hu.tilos.radio.jooqmodel.tables.Bookmark.BOOKMARK);

		setValue(0, id);
		setValue(1, radioshowId);
		setValue(2, episodeId);
		setValue(3, userId);
		setValue(4, from);
		setValue(5, to);
		setValue(6, modified);
		setValue(7, title);
		setValue(8, content);
	}
}
