/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EpisodeRecord extends org.jooq.impl.UpdatableRecordImpl<hu.tilos.radio.jooqmodel.tables.records.EpisodeRecord> implements org.jooq.Record7<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp> {

	private static final long serialVersionUID = -1794162811;

	/**
	 * Setter for <code>tilos2.episode.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>tilos2.episode.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>tilos2.episode.radioshow_id</code>.
	 */
	public void setRadioshowId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>tilos2.episode.radioshow_id</code>.
	 */
	public java.lang.Integer getRadioshowId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>tilos2.episode.textcontent_id</code>.
	 */
	public void setTextcontentId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>tilos2.episode.textcontent_id</code>.
	 */
	public java.lang.Integer getTextcontentId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>tilos2.episode.plannedFrom</code>.
	 */
	public void setPlannedfrom(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>tilos2.episode.plannedFrom</code>.
	 */
	public java.sql.Timestamp getPlannedfrom() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>tilos2.episode.plannedTo</code>.
	 */
	public void setPlannedto(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>tilos2.episode.plannedTo</code>.
	 */
	public java.sql.Timestamp getPlannedto() {
		return (java.sql.Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>tilos2.episode.realFrom</code>.
	 */
	public void setRealfrom(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>tilos2.episode.realFrom</code>.
	 */
	public java.sql.Timestamp getRealfrom() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>tilos2.episode.realTo</code>.
	 */
	public void setRealto(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>tilos2.episode.realTo</code>.
	 */
	public java.sql.Timestamp getRealto() {
		return (java.sql.Timestamp) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return hu.tilos.radio.jooqmodel.tables.Episode.EPISODE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return hu.tilos.radio.jooqmodel.tables.Episode.EPISODE.RADIOSHOW_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return hu.tilos.radio.jooqmodel.tables.Episode.EPISODE.TEXTCONTENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return hu.tilos.radio.jooqmodel.tables.Episode.EPISODE.PLANNEDFROM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return hu.tilos.radio.jooqmodel.tables.Episode.EPISODE.PLANNEDTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return hu.tilos.radio.jooqmodel.tables.Episode.EPISODE.REALFROM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return hu.tilos.radio.jooqmodel.tables.Episode.EPISODE.REALTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getRadioshowId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getTextcontentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getPlannedfrom();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getPlannedto();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getRealfrom();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getRealto();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EpisodeRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EpisodeRecord value2(java.lang.Integer value) {
		setRadioshowId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EpisodeRecord value3(java.lang.Integer value) {
		setTextcontentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EpisodeRecord value4(java.sql.Timestamp value) {
		setPlannedfrom(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EpisodeRecord value5(java.sql.Timestamp value) {
		setPlannedto(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EpisodeRecord value6(java.sql.Timestamp value) {
		setRealfrom(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EpisodeRecord value7(java.sql.Timestamp value) {
		setRealto(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EpisodeRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3, java.sql.Timestamp value4, java.sql.Timestamp value5, java.sql.Timestamp value6, java.sql.Timestamp value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EpisodeRecord
	 */
	public EpisodeRecord() {
		super(hu.tilos.radio.jooqmodel.tables.Episode.EPISODE);
	}

	/**
	 * Create a detached, initialised EpisodeRecord
	 */
	public EpisodeRecord(java.lang.Integer id, java.lang.Integer radioshowId, java.lang.Integer textcontentId, java.sql.Timestamp plannedfrom, java.sql.Timestamp plannedto, java.sql.Timestamp realfrom, java.sql.Timestamp realto) {
		super(hu.tilos.radio.jooqmodel.tables.Episode.EPISODE);

		setValue(0, id);
		setValue(1, radioshowId);
		setValue(2, textcontentId);
		setValue(3, plannedfrom);
		setValue(4, plannedto);
		setValue(5, realfrom);
		setValue(6, realto);
	}
}
