/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ListenerStatRecord extends org.jooq.impl.UpdatableRecordImpl<hu.tilos.radio.jooqmodel.tables.records.ListenerStatRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp> {

	private static final long serialVersionUID = 2068716509;

	/**
	 * Setter for <code>tilos2.listener_stat.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>tilos2.listener_stat.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>tilos2.listener_stat.type</code>.
	 */
	public void setType(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>tilos2.listener_stat.type</code>.
	 */
	public java.lang.Integer getType() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>tilos2.listener_stat.count</code>.
	 */
	public void setCount(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>tilos2.listener_stat.count</code>.
	 */
	public java.lang.Integer getCount() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>tilos2.listener_stat.date</code>.
	 */
	public void setDate(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>tilos2.listener_stat.date</code>.
	 */
	public java.sql.Timestamp getDate() {
		return (java.sql.Timestamp) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return hu.tilos.radio.jooqmodel.tables.ListenerStat.LISTENER_STAT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return hu.tilos.radio.jooqmodel.tables.ListenerStat.LISTENER_STAT.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return hu.tilos.radio.jooqmodel.tables.ListenerStat.LISTENER_STAT.COUNT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return hu.tilos.radio.jooqmodel.tables.ListenerStat.LISTENER_STAT.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getCount();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ListenerStatRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ListenerStatRecord value2(java.lang.Integer value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ListenerStatRecord value3(java.lang.Integer value) {
		setCount(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ListenerStatRecord value4(java.sql.Timestamp value) {
		setDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ListenerStatRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3, java.sql.Timestamp value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ListenerStatRecord
	 */
	public ListenerStatRecord() {
		super(hu.tilos.radio.jooqmodel.tables.ListenerStat.LISTENER_STAT);
	}

	/**
	 * Create a detached, initialised ListenerStatRecord
	 */
	public ListenerStatRecord(java.lang.Integer id, java.lang.Integer type, java.lang.Integer count, java.sql.Timestamp date) {
		super(hu.tilos.radio.jooqmodel.tables.ListenerStat.LISTENER_STAT);

		setValue(0, id);
		setValue(1, type);
		setValue(2, count);
		setValue(3, date);
	}
}
