/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MigrationVersionsRecord extends org.jooq.impl.UpdatableRecordImpl<hu.tilos.radio.jooqmodel.tables.records.MigrationVersionsRecord> implements org.jooq.Record1<java.lang.String> {

	private static final long serialVersionUID = -1738418072;

	/**
	 * Setter for <code>tilos2.migration_versions.version</code>.
	 */
	public void setVersion(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>tilos2.migration_versions.version</code>.
	 */
	public java.lang.String getVersion() {
		return (java.lang.String) getValue(0);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record1 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row1<java.lang.String> fieldsRow() {
		return (org.jooq.Row1) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row1<java.lang.String> valuesRow() {
		return (org.jooq.Row1) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return hu.tilos.radio.jooqmodel.tables.MigrationVersions.MIGRATION_VERSIONS.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MigrationVersionsRecord value1(java.lang.String value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MigrationVersionsRecord values(java.lang.String value1) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MigrationVersionsRecord
	 */
	public MigrationVersionsRecord() {
		super(hu.tilos.radio.jooqmodel.tables.MigrationVersions.MIGRATION_VERSIONS);
	}

	/**
	 * Create a detached, initialised MigrationVersionsRecord
	 */
	public MigrationVersionsRecord(java.lang.String version) {
		super(hu.tilos.radio.jooqmodel.tables.MigrationVersions.MIGRATION_VERSIONS);

		setValue(0, version);
	}
}
