/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MixRecord extends org.jooq.impl.UpdatableRecordImpl<hu.tilos.radio.jooqmodel.tables.records.MixRecord> implements org.jooq.Record7<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Date, java.lang.Integer> {

	private static final long serialVersionUID = -2045541770;

	/**
	 * Setter for <code>tilos2.mix.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>tilos2.mix.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>tilos2.mix.show_id</code>.
	 */
	public void setShowId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>tilos2.mix.show_id</code>.
	 */
	public java.lang.Integer getShowId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>tilos2.mix.author</code>.
	 */
	public void setAuthor(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>tilos2.mix.author</code>.
	 */
	public java.lang.String getAuthor() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>tilos2.mix.title</code>.
	 */
	public void setTitle(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>tilos2.mix.title</code>.
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>tilos2.mix.file</code>.
	 */
	public void setFile(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>tilos2.mix.file</code>.
	 */
	public java.lang.String getFile() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>tilos2.mix.date</code>.
	 */
	public void setDate(java.sql.Date value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>tilos2.mix.date</code>.
	 */
	public java.sql.Date getDate() {
		return (java.sql.Date) getValue(5);
	}

	/**
	 * Setter for <code>tilos2.mix.type</code>.
	 */
	public void setType(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>tilos2.mix.type</code>.
	 */
	public java.lang.Integer getType() {
		return (java.lang.Integer) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Date, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Date, java.lang.Integer> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return hu.tilos.radio.jooqmodel.tables.Mix.MIX.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return hu.tilos.radio.jooqmodel.tables.Mix.MIX.SHOW_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return hu.tilos.radio.jooqmodel.tables.Mix.MIX.AUTHOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return hu.tilos.radio.jooqmodel.tables.Mix.MIX.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return hu.tilos.radio.jooqmodel.tables.Mix.MIX.FILE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field6() {
		return hu.tilos.radio.jooqmodel.tables.Mix.MIX.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return hu.tilos.radio.jooqmodel.tables.Mix.MIX.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getShowId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getAuthor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getFile();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value6() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MixRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MixRecord value2(java.lang.Integer value) {
		setShowId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MixRecord value3(java.lang.String value) {
		setAuthor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MixRecord value4(java.lang.String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MixRecord value5(java.lang.String value) {
		setFile(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MixRecord value6(java.sql.Date value) {
		setDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MixRecord value7(java.lang.Integer value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MixRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.sql.Date value6, java.lang.Integer value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MixRecord
	 */
	public MixRecord() {
		super(hu.tilos.radio.jooqmodel.tables.Mix.MIX);
	}

	/**
	 * Create a detached, initialised MixRecord
	 */
	public MixRecord(java.lang.Integer id, java.lang.Integer showId, java.lang.String author, java.lang.String title, java.lang.String file, java.sql.Date date, java.lang.Integer type) {
		super(hu.tilos.radio.jooqmodel.tables.Mix.MIX);

		setValue(0, id);
		setValue(1, showId);
		setValue(2, author);
		setValue(3, title);
		setValue(4, file);
		setValue(5, date);
		setValue(6, type);
	}
}
