/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RadioshowRecord extends org.jooq.impl.UpdatableRecordImpl<hu.tilos.radio.jooqmodel.tables.records.RadioshowRecord> implements org.jooq.Record8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -496088171;

	/**
	 * Setter for <code>tilos2.radioshow.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>tilos2.radioshow.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>tilos2.radioshow.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>tilos2.radioshow.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>tilos2.radioshow.definition</code>.
	 */
	public void setDefinition(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>tilos2.radioshow.definition</code>.
	 */
	public java.lang.String getDefinition() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>tilos2.radioshow.alias</code>.
	 */
	public void setAlias(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>tilos2.radioshow.alias</code>.
	 */
	public java.lang.String getAlias() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>tilos2.radioshow.banner</code>.
	 */
	public void setBanner(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>tilos2.radioshow.banner</code>.
	 */
	public java.lang.String getBanner() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>tilos2.radioshow.description</code>.
	 */
	public void setDescription(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>tilos2.radioshow.description</code>.
	 */
	public java.lang.String getDescription() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>tilos2.radioshow.type</code>.
	 */
	public void setType(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>tilos2.radioshow.type</code>.
	 */
	public java.lang.Integer getType() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>tilos2.radioshow.status</code>.
	 */
	public void setStatus(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>tilos2.radioshow.status</code>.
	 */
	public java.lang.Integer getStatus() {
		return (java.lang.Integer) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return hu.tilos.radio.jooqmodel.tables.Radioshow.RADIOSHOW.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return hu.tilos.radio.jooqmodel.tables.Radioshow.RADIOSHOW.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return hu.tilos.radio.jooqmodel.tables.Radioshow.RADIOSHOW.DEFINITION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return hu.tilos.radio.jooqmodel.tables.Radioshow.RADIOSHOW.ALIAS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return hu.tilos.radio.jooqmodel.tables.Radioshow.RADIOSHOW.BANNER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return hu.tilos.radio.jooqmodel.tables.Radioshow.RADIOSHOW.DESCRIPTION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return hu.tilos.radio.jooqmodel.tables.Radioshow.RADIOSHOW.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return hu.tilos.radio.jooqmodel.tables.Radioshow.RADIOSHOW.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getDefinition();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getAlias();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getBanner();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getDescription();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RadioshowRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RadioshowRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RadioshowRecord value3(java.lang.String value) {
		setDefinition(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RadioshowRecord value4(java.lang.String value) {
		setAlias(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RadioshowRecord value5(java.lang.String value) {
		setBanner(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RadioshowRecord value6(java.lang.String value) {
		setDescription(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RadioshowRecord value7(java.lang.Integer value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RadioshowRecord value8(java.lang.Integer value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RadioshowRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.Integer value7, java.lang.Integer value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RadioshowRecord
	 */
	public RadioshowRecord() {
		super(hu.tilos.radio.jooqmodel.tables.Radioshow.RADIOSHOW);
	}

	/**
	 * Create a detached, initialised RadioshowRecord
	 */
	public RadioshowRecord(java.lang.Integer id, java.lang.String name, java.lang.String definition, java.lang.String alias, java.lang.String banner, java.lang.String description, java.lang.Integer type, java.lang.Integer status) {
		super(hu.tilos.radio.jooqmodel.tables.Radioshow.RADIOSHOW);

		setValue(0, id);
		setValue(1, name);
		setValue(2, definition);
		setValue(3, alias);
		setValue(4, banner);
		setValue(5, description);
		setValue(6, type);
		setValue(7, status);
	}
}
