/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SchedulingRecord extends org.jooq.impl.UpdatableRecordImpl<hu.tilos.radio.jooqmodel.tables.records.SchedulingRecord> implements org.jooq.Record10<java.lang.Integer, java.lang.Integer, java.lang.Short, java.sql.Date, java.lang.Short, java.lang.Short, java.lang.Short, java.lang.Short, java.sql.Date, java.sql.Date> {

	private static final long serialVersionUID = -895741347;

	/**
	 * Setter for <code>tilos2.scheduling.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>tilos2.scheduling.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>tilos2.scheduling.radioshow_id</code>.
	 */
	public void setRadioshowId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>tilos2.scheduling.radioshow_id</code>.
	 */
	public java.lang.Integer getRadioshowId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>tilos2.scheduling.weekType</code>.
	 */
	public void setWeektype(java.lang.Short value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>tilos2.scheduling.weekType</code>.
	 */
	public java.lang.Short getWeektype() {
		return (java.lang.Short) getValue(2);
	}

	/**
	 * Setter for <code>tilos2.scheduling.base</code>.
	 */
	public void setBase(java.sql.Date value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>tilos2.scheduling.base</code>.
	 */
	public java.sql.Date getBase() {
		return (java.sql.Date) getValue(3);
	}

	/**
	 * Setter for <code>tilos2.scheduling.weekDay</code>.
	 */
	public void setWeekday(java.lang.Short value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>tilos2.scheduling.weekDay</code>.
	 */
	public java.lang.Short getWeekday() {
		return (java.lang.Short) getValue(4);
	}

	/**
	 * Setter for <code>tilos2.scheduling.hourFrom</code>.
	 */
	public void setHourfrom(java.lang.Short value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>tilos2.scheduling.hourFrom</code>.
	 */
	public java.lang.Short getHourfrom() {
		return (java.lang.Short) getValue(5);
	}

	/**
	 * Setter for <code>tilos2.scheduling.minFrom</code>.
	 */
	public void setMinfrom(java.lang.Short value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>tilos2.scheduling.minFrom</code>.
	 */
	public java.lang.Short getMinfrom() {
		return (java.lang.Short) getValue(6);
	}

	/**
	 * Setter for <code>tilos2.scheduling.duration</code>.
	 */
	public void setDuration(java.lang.Short value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>tilos2.scheduling.duration</code>.
	 */
	public java.lang.Short getDuration() {
		return (java.lang.Short) getValue(7);
	}

	/**
	 * Setter for <code>tilos2.scheduling.validFrom</code>.
	 */
	public void setValidfrom(java.sql.Date value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>tilos2.scheduling.validFrom</code>.
	 */
	public java.sql.Date getValidfrom() {
		return (java.sql.Date) getValue(8);
	}

	/**
	 * Setter for <code>tilos2.scheduling.validTo</code>.
	 */
	public void setValidto(java.sql.Date value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>tilos2.scheduling.validTo</code>.
	 */
	public java.sql.Date getValidto() {
		return (java.sql.Date) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.Integer, java.lang.Integer, java.lang.Short, java.sql.Date, java.lang.Short, java.lang.Short, java.lang.Short, java.lang.Short, java.sql.Date, java.sql.Date> fieldsRow() {
		return (org.jooq.Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.Integer, java.lang.Integer, java.lang.Short, java.sql.Date, java.lang.Short, java.lang.Short, java.lang.Short, java.lang.Short, java.sql.Date, java.sql.Date> valuesRow() {
		return (org.jooq.Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING.RADIOSHOW_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field3() {
		return hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING.WEEKTYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field4() {
		return hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING.BASE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field5() {
		return hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING.WEEKDAY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field6() {
		return hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING.HOURFROM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field7() {
		return hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING.MINFROM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field8() {
		return hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING.DURATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field9() {
		return hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING.VALIDFROM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field10() {
		return hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING.VALIDTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getRadioshowId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value3() {
		return getWeektype();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value4() {
		return getBase();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value5() {
		return getWeekday();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value6() {
		return getHourfrom();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value7() {
		return getMinfrom();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value8() {
		return getDuration();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value9() {
		return getValidfrom();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value10() {
		return getValidto();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchedulingRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchedulingRecord value2(java.lang.Integer value) {
		setRadioshowId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchedulingRecord value3(java.lang.Short value) {
		setWeektype(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchedulingRecord value4(java.sql.Date value) {
		setBase(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchedulingRecord value5(java.lang.Short value) {
		setWeekday(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchedulingRecord value6(java.lang.Short value) {
		setHourfrom(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchedulingRecord value7(java.lang.Short value) {
		setMinfrom(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchedulingRecord value8(java.lang.Short value) {
		setDuration(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchedulingRecord value9(java.sql.Date value) {
		setValidfrom(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchedulingRecord value10(java.sql.Date value) {
		setValidto(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public SchedulingRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Short value3, java.sql.Date value4, java.lang.Short value5, java.lang.Short value6, java.lang.Short value7, java.lang.Short value8, java.sql.Date value9, java.sql.Date value10) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached SchedulingRecord
	 */
	public SchedulingRecord() {
		super(hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING);
	}

	/**
	 * Create a detached, initialised SchedulingRecord
	 */
	public SchedulingRecord(java.lang.Integer id, java.lang.Integer radioshowId, java.lang.Short weektype, java.sql.Date base, java.lang.Short weekday, java.lang.Short hourfrom, java.lang.Short minfrom, java.lang.Short duration, java.sql.Date validfrom, java.sql.Date validto) {
		super(hu.tilos.radio.jooqmodel.tables.Scheduling.SCHEDULING);

		setValue(0, id);
		setValue(1, radioshowId);
		setValue(2, weektype);
		setValue(3, base);
		setValue(4, weekday);
		setValue(5, hourfrom);
		setValue(6, minfrom);
		setValue(7, duration);
		setValue(8, validfrom);
		setValue(9, validto);
	}
}
