/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagTextcontentRecord extends org.jooq.impl.UpdatableRecordImpl<hu.tilos.radio.jooqmodel.tables.records.TagTextcontentRecord> implements org.jooq.Record2<java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -1672375748;

	/**
	 * Setter for <code>tilos2.tag_textcontent.textcontent_id</code>.
	 */
	public void setTextcontentId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>tilos2.tag_textcontent.textcontent_id</code>.
	 */
	public java.lang.Integer getTextcontentId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>tilos2.tag_textcontent.tag_id</code>.
	 */
	public void setTagId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>tilos2.tag_textcontent.tag_id</code>.
	 */
	public java.lang.Integer getTagId() {
		return (java.lang.Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.Integer, java.lang.Integer> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return hu.tilos.radio.jooqmodel.tables.TagTextcontent.TAG_TEXTCONTENT.TEXTCONTENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return hu.tilos.radio.jooqmodel.tables.TagTextcontent.TAG_TEXTCONTENT.TAG_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getTextcontentId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getTagId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TagTextcontentRecord value1(java.lang.Integer value) {
		setTextcontentId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TagTextcontentRecord value2(java.lang.Integer value) {
		setTagId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TagTextcontentRecord values(java.lang.Integer value1, java.lang.Integer value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TagTextcontentRecord
	 */
	public TagTextcontentRecord() {
		super(hu.tilos.radio.jooqmodel.tables.TagTextcontent.TAG_TEXTCONTENT);
	}

	/**
	 * Create a detached, initialised TagTextcontentRecord
	 */
	public TagTextcontentRecord(java.lang.Integer textcontentId, java.lang.Integer tagId) {
		super(hu.tilos.radio.jooqmodel.tables.TagTextcontent.TAG_TEXTCONTENT);

		setValue(0, textcontentId);
		setValue(1, tagId);
	}
}
