/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TextcontentRecord extends org.jooq.impl.UpdatableRecordImpl<hu.tilos.radio.jooqmodel.tables.records.TextcontentRecord> implements org.jooq.Record9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -27922628;

	/**
	 * Setter for <code>tilos2.textcontent.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>tilos2.textcontent.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>tilos2.textcontent.title</code>.
	 */
	public void setTitle(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>tilos2.textcontent.title</code>.
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>tilos2.textcontent.type</code>.
	 */
	public void setType(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>tilos2.textcontent.type</code>.
	 */
	public java.lang.String getType() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>tilos2.textcontent.format</code>.
	 */
	public void setFormat(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>tilos2.textcontent.format</code>.
	 */
	public java.lang.String getFormat() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>tilos2.textcontent.content</code>.
	 */
	public void setContent(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>tilos2.textcontent.content</code>.
	 */
	public java.lang.String getContent() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>tilos2.textcontent.created</code>.
	 */
	public void setCreated(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>tilos2.textcontent.created</code>.
	 */
	public java.sql.Timestamp getCreated() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>tilos2.textcontent.modified</code>.
	 */
	public void setModified(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>tilos2.textcontent.modified</code>.
	 */
	public java.sql.Timestamp getModified() {
		return (java.sql.Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>tilos2.textcontent.author</code>.
	 */
	public void setAuthor(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>tilos2.textcontent.author</code>.
	 */
	public java.lang.String getAuthor() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>tilos2.textcontent.alias</code>.
	 */
	public void setAlias(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>tilos2.textcontent.alias</code>.
	 */
	public java.lang.String getAlias() {
		return (java.lang.String) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT.FORMAT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT.CONTENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT.MODIFIED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT.AUTHOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT.ALIAS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getFormat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getContent();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getModified();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getAuthor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getAlias();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TextcontentRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TextcontentRecord value2(java.lang.String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TextcontentRecord value3(java.lang.String value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TextcontentRecord value4(java.lang.String value) {
		setFormat(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TextcontentRecord value5(java.lang.String value) {
		setContent(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TextcontentRecord value6(java.sql.Timestamp value) {
		setCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TextcontentRecord value7(java.sql.Timestamp value) {
		setModified(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TextcontentRecord value8(java.lang.String value) {
		setAuthor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TextcontentRecord value9(java.lang.String value) {
		setAlias(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TextcontentRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.sql.Timestamp value6, java.sql.Timestamp value7, java.lang.String value8, java.lang.String value9) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TextcontentRecord
	 */
	public TextcontentRecord() {
		super(hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT);
	}

	/**
	 * Create a detached, initialised TextcontentRecord
	 */
	public TextcontentRecord(java.lang.Integer id, java.lang.String title, java.lang.String type, java.lang.String format, java.lang.String content, java.sql.Timestamp created, java.sql.Timestamp modified, java.lang.String author, java.lang.String alias) {
		super(hu.tilos.radio.jooqmodel.tables.Textcontent.TEXTCONTENT);

		setValue(0, id);
		setValue(1, title);
		setValue(2, type);
		setValue(3, format);
		setValue(4, content);
		setValue(5, created);
		setValue(6, modified);
		setValue(7, author);
		setValue(8, alias);
	}
}
