/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthorUrl implements java.io.Serializable {

	private static final long serialVersionUID = 121628383;

	private java.lang.Integer authorId;
	private java.lang.Integer urlId;

	public AuthorUrl() {}

	public AuthorUrl(
		java.lang.Integer authorId,
		java.lang.Integer urlId
	) {
		this.authorId = authorId;
		this.urlId = urlId;
	}

	public java.lang.Integer getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(java.lang.Integer authorId) {
		this.authorId = authorId;
	}

	public java.lang.Integer getUrlId() {
		return this.urlId;
	}

	public void setUrlId(java.lang.Integer urlId) {
		this.urlId = urlId;
	}
}
