/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Author implements java.io.Serializable {

	private static final long serialVersionUID = -1096328086;

	private java.lang.Integer id;
	private java.lang.Integer userId;
	private java.lang.String  name;
	private java.lang.String  alias;
	private java.lang.String  photo;
	private java.lang.String  avatar;
	private java.lang.String  introduction;
	private java.lang.String  email;

	public Author() {}

	public Author(
		java.lang.Integer id,
		java.lang.Integer userId,
		java.lang.String  name,
		java.lang.String  alias,
		java.lang.String  photo,
		java.lang.String  avatar,
		java.lang.String  introduction,
		java.lang.String  email
	) {
		this.id = id;
		this.userId = userId;
		this.name = name;
		this.alias = alias;
		this.photo = photo;
		this.avatar = avatar;
		this.introduction = introduction;
		this.email = email;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.Integer userId) {
		this.userId = userId;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getAlias() {
		return this.alias;
	}

	public void setAlias(java.lang.String alias) {
		this.alias = alias;
	}

	public java.lang.String getPhoto() {
		return this.photo;
	}

	public void setPhoto(java.lang.String photo) {
		this.photo = photo;
	}

	public java.lang.String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(java.lang.String avatar) {
		this.avatar = avatar;
	}

	public java.lang.String getIntroduction() {
		return this.introduction;
	}

	public void setIntroduction(java.lang.String introduction) {
		this.introduction = introduction;
	}

	public java.lang.String getEmail() {
		return this.email;
	}

	public void setEmail(java.lang.String email) {
		this.email = email;
	}
}
