/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Contribution implements java.io.Serializable {

	private static final long serialVersionUID = 837639849;

	private java.lang.Integer id;
	private java.lang.Integer radioshowId;
	private java.lang.Integer authorId;
	private java.lang.String  nick;

	public Contribution() {}

	public Contribution(
		java.lang.Integer id,
		java.lang.Integer radioshowId,
		java.lang.Integer authorId,
		java.lang.String  nick
	) {
		this.id = id;
		this.radioshowId = radioshowId;
		this.authorId = authorId;
		this.nick = nick;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getRadioshowId() {
		return this.radioshowId;
	}

	public void setRadioshowId(java.lang.Integer radioshowId) {
		this.radioshowId = radioshowId;
	}

	public java.lang.Integer getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(java.lang.Integer authorId) {
		this.authorId = authorId;
	}

	public java.lang.String getNick() {
		return this.nick;
	}

	public void setNick(java.lang.String nick) {
		this.nick = nick;
	}
}
