/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ListenerStat implements java.io.Serializable {

	private static final long serialVersionUID = -1411242219;

	private java.lang.Integer  id;
	private java.lang.Integer  type;
	private java.lang.Integer  count;
	private java.sql.Timestamp date;

	public ListenerStat() {}

	public ListenerStat(
		java.lang.Integer  id,
		java.lang.Integer  type,
		java.lang.Integer  count,
		java.sql.Timestamp date
	) {
		this.id = id;
		this.type = type;
		this.count = count;
		this.date = date;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getType() {
		return this.type;
	}

	public void setType(java.lang.Integer type) {
		this.type = type;
	}

	public java.lang.Integer getCount() {
		return this.count;
	}

	public void setCount(java.lang.Integer count) {
		this.count = count;
	}

	public java.sql.Timestamp getDate() {
		return this.date;
	}

	public void setDate(java.sql.Timestamp date) {
		this.date = date;
	}
}
