/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mix implements java.io.Serializable {

	private static final long serialVersionUID = -301739327;

	private java.lang.Integer id;
	private java.lang.Integer showId;
	private java.lang.String  author;
	private java.lang.String  title;
	private java.lang.String  file;
	private java.sql.Date     date;
	private java.lang.Integer type;

	public Mix() {}

	public Mix(
		java.lang.Integer id,
		java.lang.Integer showId,
		java.lang.String  author,
		java.lang.String  title,
		java.lang.String  file,
		java.sql.Date     date,
		java.lang.Integer type
	) {
		this.id = id;
		this.showId = showId;
		this.author = author;
		this.title = title;
		this.file = file;
		this.date = date;
		this.type = type;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getShowId() {
		return this.showId;
	}

	public void setShowId(java.lang.Integer showId) {
		this.showId = showId;
	}

	public java.lang.String getAuthor() {
		return this.author;
	}

	public void setAuthor(java.lang.String author) {
		this.author = author;
	}

	public java.lang.String getTitle() {
		return this.title;
	}

	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public java.lang.String getFile() {
		return this.file;
	}

	public void setFile(java.lang.String file) {
		this.file = file;
	}

	public java.sql.Date getDate() {
		return this.date;
	}

	public void setDate(java.sql.Date date) {
		this.date = date;
	}

	public java.lang.Integer getType() {
		return this.type;
	}

	public void setType(java.lang.Integer type) {
		this.type = type;
	}
}
