/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Radioshow implements java.io.Serializable {

	private static final long serialVersionUID = -341521257;

	private java.lang.Integer id;
	private java.lang.String  name;
	private java.lang.String  definition;
	private java.lang.String  alias;
	private java.lang.String  banner;
	private java.lang.String  description;
	private java.lang.Integer type;
	private java.lang.Integer status;

	public Radioshow() {}

	public Radioshow(
		java.lang.Integer id,
		java.lang.String  name,
		java.lang.String  definition,
		java.lang.String  alias,
		java.lang.String  banner,
		java.lang.String  description,
		java.lang.Integer type,
		java.lang.Integer status
	) {
		this.id = id;
		this.name = name;
		this.definition = definition;
		this.alias = alias;
		this.banner = banner;
		this.description = description;
		this.type = type;
		this.status = status;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getDefinition() {
		return this.definition;
	}

	public void setDefinition(java.lang.String definition) {
		this.definition = definition;
	}

	public java.lang.String getAlias() {
		return this.alias;
	}

	public void setAlias(java.lang.String alias) {
		this.alias = alias;
	}

	public java.lang.String getBanner() {
		return this.banner;
	}

	public void setBanner(java.lang.String banner) {
		this.banner = banner;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.Integer getType() {
		return this.type;
	}

	public void setType(java.lang.Integer type) {
		this.type = type;
	}

	public java.lang.Integer getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.Integer status) {
		this.status = status;
	}
}
