/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Role implements java.io.Serializable {

	private static final long serialVersionUID = 238128017;

	private java.lang.Integer id;
	private java.lang.Integer parentRoleId;
	private java.lang.String  name;

	public Role() {}

	public Role(
		java.lang.Integer id,
		java.lang.Integer parentRoleId,
		java.lang.String  name
	) {
		this.id = id;
		this.parentRoleId = parentRoleId;
		this.name = name;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getParentRoleId() {
		return this.parentRoleId;
	}

	public void setParentRoleId(java.lang.Integer parentRoleId) {
		this.parentRoleId = parentRoleId;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}
}
