/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Scheduling implements java.io.Serializable {

	private static final long serialVersionUID = 464812329;

	private java.lang.Integer id;
	private java.lang.Integer radioshowId;
	private java.lang.Short   weektype;
	private java.sql.Date     base;
	private java.lang.Short   weekday;
	private java.lang.Short   hourfrom;
	private java.lang.Short   minfrom;
	private java.lang.Short   duration;
	private java.sql.Date     validfrom;
	private java.sql.Date     validto;

	public Scheduling() {}

	public Scheduling(
		java.lang.Integer id,
		java.lang.Integer radioshowId,
		java.lang.Short   weektype,
		java.sql.Date     base,
		java.lang.Short   weekday,
		java.lang.Short   hourfrom,
		java.lang.Short   minfrom,
		java.lang.Short   duration,
		java.sql.Date     validfrom,
		java.sql.Date     validto
	) {
		this.id = id;
		this.radioshowId = radioshowId;
		this.weektype = weektype;
		this.base = base;
		this.weekday = weekday;
		this.hourfrom = hourfrom;
		this.minfrom = minfrom;
		this.duration = duration;
		this.validfrom = validfrom;
		this.validto = validto;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getRadioshowId() {
		return this.radioshowId;
	}

	public void setRadioshowId(java.lang.Integer radioshowId) {
		this.radioshowId = radioshowId;
	}

	public java.lang.Short getWeektype() {
		return this.weektype;
	}

	public void setWeektype(java.lang.Short weektype) {
		this.weektype = weektype;
	}

	public java.sql.Date getBase() {
		return this.base;
	}

	public void setBase(java.sql.Date base) {
		this.base = base;
	}

	public java.lang.Short getWeekday() {
		return this.weekday;
	}

	public void setWeekday(java.lang.Short weekday) {
		this.weekday = weekday;
	}

	public java.lang.Short getHourfrom() {
		return this.hourfrom;
	}

	public void setHourfrom(java.lang.Short hourfrom) {
		this.hourfrom = hourfrom;
	}

	public java.lang.Short getMinfrom() {
		return this.minfrom;
	}

	public void setMinfrom(java.lang.Short minfrom) {
		this.minfrom = minfrom;
	}

	public java.lang.Short getDuration() {
		return this.duration;
	}

	public void setDuration(java.lang.Short duration) {
		this.duration = duration;
	}

	public java.sql.Date getValidfrom() {
		return this.validfrom;
	}

	public void setValidfrom(java.sql.Date validfrom) {
		this.validfrom = validfrom;
	}

	public java.sql.Date getValidto() {
		return this.validto;
	}

	public void setValidto(java.sql.Date validto) {
		this.validto = validto;
	}
}
