/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShowUrl implements java.io.Serializable {

	private static final long serialVersionUID = 1175037915;

	private java.lang.Integer radioshowId;
	private java.lang.Integer urlId;

	public ShowUrl() {}

	public ShowUrl(
		java.lang.Integer radioshowId,
		java.lang.Integer urlId
	) {
		this.radioshowId = radioshowId;
		this.urlId = urlId;
	}

	public java.lang.Integer getRadioshowId() {
		return this.radioshowId;
	}

	public void setRadioshowId(java.lang.Integer radioshowId) {
		this.radioshowId = radioshowId;
	}

	public java.lang.Integer getUrlId() {
		return this.urlId;
	}

	public void setUrlId(java.lang.Integer urlId) {
		this.urlId = urlId;
	}
}
