/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tag implements java.io.Serializable {

	private static final long serialVersionUID = 690448667;

	private java.lang.Integer id;
	private java.lang.String  name;
	private java.lang.Integer type;

	public Tag() {}

	public Tag(
		java.lang.Integer id,
		java.lang.String  name,
		java.lang.Integer type
	) {
		this.id = id;
		this.name = name;
		this.type = type;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Integer getType() {
		return this.type;
	}

	public void setType(java.lang.Integer type) {
		this.type = type;
	}
}
