/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TagTextcontent implements java.io.Serializable {

	private static final long serialVersionUID = 498780451;

	private java.lang.Integer textcontentId;
	private java.lang.Integer tagId;

	public TagTextcontent() {}

	public TagTextcontent(
		java.lang.Integer textcontentId,
		java.lang.Integer tagId
	) {
		this.textcontentId = textcontentId;
		this.tagId = tagId;
	}

	public java.lang.Integer getTextcontentId() {
		return this.textcontentId;
	}

	public void setTextcontentId(java.lang.Integer textcontentId) {
		this.textcontentId = textcontentId;
	}

	public java.lang.Integer getTagId() {
		return this.tagId;
	}

	public void setTagId(java.lang.Integer tagId) {
		this.tagId = tagId;
	}
}
