/**
 * This class is generated by jOOQ
 */
package hu.tilos.radio.jooqmodel.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Textcontent implements java.io.Serializable {

	private static final long serialVersionUID = -1469236663;

	private java.lang.Integer  id;
	private java.lang.String   title;
	private java.lang.String   type;
	private java.lang.String   format;
	private java.lang.String   content;
	private java.sql.Timestamp created;
	private java.sql.Timestamp modified;
	private java.lang.String   author;
	private java.lang.String   alias;

	public Textcontent() {}

	public Textcontent(
		java.lang.Integer  id,
		java.lang.String   title,
		java.lang.String   type,
		java.lang.String   format,
		java.lang.String   content,
		java.sql.Timestamp created,
		java.sql.Timestamp modified,
		java.lang.String   author,
		java.lang.String   alias
	) {
		this.id = id;
		this.title = title;
		this.type = type;
		this.format = format;
		this.content = content;
		this.created = created;
		this.modified = modified;
		this.author = author;
		this.alias = alias;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getTitle() {
		return this.title;
	}

	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getFormat() {
		return this.format;
	}

	public void setFormat(java.lang.String format) {
		this.format = format;
	}

	public java.lang.String getContent() {
		return this.content;
	}

	public void setContent(java.lang.String content) {
		this.content = content;
	}

	public java.sql.Timestamp getCreated() {
		return this.created;
	}

	public void setCreated(java.sql.Timestamp created) {
		this.created = created;
	}

	public java.sql.Timestamp getModified() {
		return this.modified;
	}

	public void setModified(java.sql.Timestamp modified) {
		this.modified = modified;
	}

	public java.lang.String getAuthor() {
		return this.author;
	}

	public void setAuthor(java.lang.String author) {
		this.author = author;
	}

	public java.lang.String getAlias() {
		return this.alias;
	}

	public void setAlias(java.lang.String alias) {
		this.alias = alias;
	}
}
